"""Publieke facade van het MDM-component (fase 2, #400).

Masterdata (personen, gezinnen, adressen, contactgegevens, postcodes,
organisaties, codes) wordt buiten dit component uitsluitend via deze module
aangesproken. Soft-ref-patroon (§6): consumenten bewaren waarde-id's
(bv. ``person_id`` als integer, zonder FK) en lezen via ``resolve()``.
"""

# CR-12: this domain's code lists belong to the public facade, so that another
# domain reaches an FK target and an enum through one door.
from app.domains.mdm.change_lines import (  # noqa: F401
    FieldChange,
    contact_change,
)
from app.domains.mdm.codes import (  # noqa: F401,E402
    CONTACT,
    CONTACT_TYPE,
    EXTERNAL,
    EXTERNAL_SOURCE,
    GENDER,
    IDENTIFICATION_SCHEME,
    LANGUAGE,
    LEGAL_FORM,
    ORGANIZATION_RELATION_TYPE,
    ORGANIZATION_TYPE,
    PAYMENT_METHOD,
    RELATION_TYPE,
    TENANT_KIND,
)

# The family portal's mutations (CR-13 phase 3): master data changed by its owner.
from app.domains.mdm.household_doors import household_refusals_as_http  # noqa: F401

# The one save of a household (CR-11 pilot B, #1590).
from app.domains.mdm.household_form import household_from_form  # noqa: F401
from app.domains.mdm.household_save import (  # noqa: F401
    HouseholdSave,
    HouseholdSaveRefused,
    PersonRow,
    save_household,
    save_person,
)
from app.domains.mdm.household_service import (  # noqa: F401  # noqa: F401
    ADDED_RELATIONS,
    CannotRemoveSelf,
    HouseholdNotFound,
    HouseholdRefused,
    MainMemberStays,
    OutsideHousehold,
    PersonNotFound,
    actor_of,
    add_household_person,
    chosen_relation,
    default_relation,
    household_of,
    household_person,
    person_payload,
    remove_household_person,
    update_household_person,
)
from app.domains.mdm.models import (  # noqa: F401
    MEMBER_REPORT_IMPORT,
    Address,
    AddressHistory,
    BankAccount,
    ContactDetail,
    ContactDetailHistory,
    ContactTypeCode,
    ContactTypeLabel,
    EmailAddressInUse,
    ExternalNumber,
    GenderCode,
    GenderLabel,
    IdentificationScheme,
    IdentificationSchemeLabel,
    LegalForm,
    LegalFormCode,
    LegalFormLabel,
    MainMemberMobileMissing,
    MasterDataError,
    Member,
    MemberHistory,
    MemberPerson,
    MemberPersonHistory,
    Organization,
    OrganizationIdentification,
    OrganizationPerson,
    OrganizationRelationType,
    OrganizationRelationTypeLabel,
    OrganizationType,
    OrganizationTypeCode,
    OrganizationTypeLabel,
    PaymentMethod,
    PaymentMethodCode,
    PaymentMethodLabel,
    Person,
    PersonDetailsMissing,
    PersonHistory,
    PostalCode,
    RelationType,
    RelationTypeCode,
    TenantKind,
)

# De organisatie als rechtspersoon staat sinds #971 apart van de tenant als site.
# Zie de moduledocstring daar: de ACCOUNT-organisatie is geen tenant, en zolang deze
# functies onder "tenant" hingen, las de code alsof zo'n organisatie niet bestond.
from app.domains.mdm.organization_service import (  # noqa: F401
    ALLE_ORGANISATIEVELDEN,
    legal_form_options,
    organization_address,
    organization_details,
    organization_options,
    save_organization,
    update_organization_address,
    update_organization_details,
)
from app.domains.mdm.service import (  # noqa: F401  # noqa: F401  # noqa: E402,F401  # noqa: F401
    BOARD_MEETING,
    CirclePerson,
    MergeError,
    PersonMatch,
    add_email_address,
    add_to_circle,
    admin_code_lists,
    apply_email_rows,
    create_person_for_circle,
    email_addresses_of_members,
    email_refusal,
    end_circle_relation,
    family_registrations,
    form_code_lists,
    gezin_tabs,
    household_ids,
    households_as_named,
    is_member,
    list_persons,
    list_postal_codes,
    make_email_primary,
    merge_persons,
    name_parts,
    new_contact_detail,
    organization_circle,
    person_name_parts,
    remove_email_address,
    require_email_free,
    resolve,
    search_persons,
    unmerge_person,
    upsert_primary_contact,
)
from app.domains.mdm.tenant_lookup import (  # noqa: F401
    current_enabled_modules,
    enabled_modules,
    invalidate_tenant_codes,
    module_enabled,
    platform_tenant_id,
    tenant_codes,
)
from app.domains.mdm.tenant_service import (  # noqa: F401
    CREATABLE_TENANT_KINDS,
    ModuleRefused,
    OngeldigeInstelling,
    TenantFout,
    active_sites_by_account,
    create_account,
    create_tenant,
    list_accounts,
    list_manageable_tenants,
    list_units,
    platform_org,
    save_tenant,
    secrets_gezet,
    set_modules,
    update_tenant_settings,
)

# ── Doorgangen naar de ledenimport ───────────────────────────────────────────
# De implementatie blijft in `import_router.py` (het is één domeinbewerking die
# het scherm alleen aanroept); de weg ernaartoe loopt via de facade (#635 I).


async def import_preview(db, file, admin=None):
    from app.domains.mdm.import_router import preview as _impl

    return await _impl(file=file, db=db, admin=admin)


def import_commit(db, token: str, admin=None):
    from app.domains.mdm.import_router import CommitRequest
    from app.domains.mdm.import_router import commit as _impl

    return _impl(CommitRequest(token=token), db=db, admin=admin)


__all__ = [
    "LANGUAGE",
    "family_registrations",
    "gezin_tabs",
    "name_parts",
    "person_name_parts",
    "OngeldigeInstelling",
    "TenantFout",
    "CREATABLE_TENANT_KINDS",
    "admin_code_lists",
    "import_commit",
    "import_preview",
    "ModuleRefused",
    "create_account",
    "create_tenant",
    "form_code_lists",
    "list_persons",
    "PersonMatch",
    "search_persons",
    "is_member",
    "household_ids",
    "list_postal_codes",
    "list_accounts",
    "active_sites_by_account",
    "list_units",
    "secrets_gezet",
    "update_tenant_settings",
    "platform_tenant_id",
    "organization_details",
    "update_organization_details",
    "save_organization",
    "organization_address",
    "update_organization_address",
    "organization_options",
    "legal_form_options",
    "ALLE_ORGANISATIEVELDEN",
    "list_manageable_tenants",
    "platform_org",
    "Address",
    "AddressHistory",
    "ContactDetail",
    "ContactDetailHistory",
    "ContactTypeCode",
    "ExternalNumber",
    "GenderCode",
    "Member",
    "BankAccount",
    "OrganizationIdentification",
    "IdentificationScheme",
    "IdentificationSchemeLabel",
    "MemberHistory",
    "MemberPerson",
    "MemberPersonHistory",
    "Organization",
    "PaymentMethod",
    "PaymentMethodCode",
    "PaymentMethodLabel",
    "PAYMENT_METHOD",
    "ContactTypeLabel",
    "GenderLabel",
    "LegalForm",
    "LegalFormCode",
    "LegalFormLabel",
    "OrganizationType",
    "TenantKind",
    "OrganizationTypeCode",
    "OrganizationTypeLabel",
    "RelationType",
    "GENDER",
    "CONTACT",
    "CONTACT_TYPE",
    "EXTERNAL",
    "EXTERNAL_SOURCE",
    "RELATION_TYPE",
    "LEGAL_FORM",
    "TENANT_KIND",
    "ORGANIZATION_TYPE",
    "ORGANIZATION_RELATION_TYPE",
    "IDENTIFICATION_SCHEME",
    "Person",
    "PersonHistory",
    "PostalCode",
    "RelationTypeCode",
    "MergeError",
    "merge_persons",
    "resolve",
    "unmerge_person",
    "tenant_codes",
    "invalidate_tenant_codes",
    # CR-19 #1475: the enabled module set per tenant.
    "enabled_modules",
    "current_enabled_modules",
    "module_enabled",
    "save_tenant",
    "set_modules",
    "BOARD_MEETING",
    "CirclePerson",
    "OrganizationPerson",
    "OrganizationRelationType",
    "OrganizationRelationTypeLabel",
    "add_to_circle",
    "create_person_for_circle",
    "end_circle_relation",
    "households_as_named",
    "organization_circle",
    "email_addresses_of_members",
    "upsert_primary_contact",
    "FieldChange",
    "contact_change",
    "add_email_address",
    "email_refusal",
    "new_contact_detail",
    "require_email_free",
    "EmailAddressInUse",
    "apply_email_rows",
    "make_email_primary",
    "remove_email_address",
    "MasterDataError",
    "HouseholdNotFound",
    "PersonNotFound",
    "OutsideHousehold",
    "CannotRemoveSelf",
    "HouseholdRefused",
    "household_of",
    "household_person",
    "update_household_person",
    "add_household_person",
    "remove_household_person",
    "person_payload",
    "household_refusals_as_http",
    "HouseholdSave",
    "HouseholdSaveRefused",
    "household_from_form",
    "default_relation",
    "chosen_relation",
    "ADDED_RELATIONS",
    "MainMemberStays",
    "PersonRow",
    "save_household",
    "save_person",
    "actor_of",
    "MainMemberMobileMissing",
    "PersonDetailsMissing",
    "MEMBER_REPORT_IMPORT",
]
