"""Publieke facade van het auth-component (fase 1b, #399).

Andere componenten en de oude wereld importeren authenticatie/autorisatie
uitsluitend via deze module. De implementatie leeft in service.py (JWT +
rol-dependencies), session.py (HttpOnly-sessie + CSRF voor server-rendered
schermen), member_identity.py (e-mail -> Person/gezin) en router.py
(login-flow + gebruikersbeheer).
"""

# CR-12 phase 2: the role list belongs to this domain's public surface, so
# that `workflow` reaches its FK target and its enum through one door.
from app.domains.auth.codes import LOGIN_PURPOSE, ROLE  # noqa: F401
from app.domains.auth.login import (  # noqa: F401
    AccountRequest,
    AccountRequestInvalid,
    Consumed,
    check_otp,
    consume_code,
    consume_link,
    consume_magic_link,
    start_account,
    start_login,
)
from app.domains.auth.member_identity import (  # noqa: F401
    address_says_nobody,
    find_persons_by_email,
    has_household,
    login_person_for_email,
    resolve_household,
    sign_in_identity,
)
from app.domains.auth.models import (  # noqa: F401
    ApiKey,
    LoginPurpose,
    LoginToken,
    Role,
    RoleCode,
    RoleLabel,
    User,
    UserRole,
)
from app.domains.auth.service import (  # noqa: F401
    API_KEY_HEADER,
    create_access_token,
    decode_token,
    get_current_admin,
    get_current_identity,
    get_current_member,
    get_user_role_rows,
    get_user_roles,
    hash_api_key,
    landing_for,
    require_api_key,
    require_member,
    require_roles,
)
from app.domains.auth.session import (  # noqa: F401
    SESSION_COOKIE,
    admin_user_by_email,
    admits_admin_ui,
    back_office_home,
    csrf_from_request,
    csrf_token_for,
    make_session_value,
    may_mutate_payments,
    may_use_admin_assistant,
    may_view_payments,
    read_session_value,
    require_admin_ui,
    require_csrf,
    require_finance_mutation,
    require_finance_ui,
    require_operator_ui,
    require_platform_operator_ui,
    require_tenant_workspace,
    session_cookie_secure,
    set_session_cookie,
)
from app.domains.auth.users import (  # noqa: F401
    is_platform_workspace,
    list_assignable_roles,
    role_options,
)

__all__ = [
    "check_otp",
    "consume_magic_link",
    "list_assignable_roles",
    "role_options",
    "start_login",
    "find_persons_by_email",
    "login_person_for_email",
    "resolve_household",
    "has_household",
    "address_says_nobody",
    "sign_in_identity",
    "ApiKey",
    "LoginPurpose",
    "LOGIN_PURPOSE",
    "LoginToken",
    "Role",
    "RoleCode",
    "RoleLabel",
    "ROLE",
    "User",
    "UserRole",
    "API_KEY_HEADER",
    "hash_api_key",
    "require_api_key",
    "create_access_token",
    "decode_token",
    "get_current_admin",
    "get_current_identity",
    "get_current_member",
    "get_user_role_rows",
    "get_user_roles",
    "landing_for",
    "require_member",
    "require_roles",
    "SESSION_COOKIE",
    "admin_user_by_email",
    "admits_admin_ui",
    "back_office_home",
    "csrf_from_request",
    "csrf_token_for",
    "make_session_value",
    "read_session_value",
    "require_admin_ui",
    "may_mutate_payments",
    "require_finance_mutation",
    "may_view_payments",
    "may_use_admin_assistant",
    "require_finance_ui",
    "require_operator_ui",
    "require_platform_operator_ui",
    "require_tenant_workspace",
    "is_platform_workspace",
    "require_csrf",
    "session_cookie_secure",
    "set_session_cookie",
]
