"""Publieke facade van de media-capaciteit (fase 4c, #404).

Opslag-adapter: vandaag LargeBinary in Postgres (mee in de ene backup);
`MediaAsset.data`/`thumbnail` zijn de enige opslagvelden — een latere
object-storage-adapter wisselt achter deze facade.
"""

# CR-12 phase 4: the kind of a file as a code list.
from app.domains.media.codes import MEDIA_KIND  # noqa: F401
from app.domains.media.extraction import (  # noqa: F401
    EXTRACTABLE_KINDS,
    _extract_pdf_text_layer,
    extract_document_text,
    update_media_extracted_text,
)
from app.domains.media.models import (  # noqa: F401
    MediaAsset,
    MediaAssetTag,
    MediaKind,
    MediaTag,
    MediaThumbsUp,
    as_media_kind,
)
from app.domains.media.svg import SVG_CONTENT_TYPE  # noqa: F401  (#989)

__all__ = [
    # #1470: tags, shown as a tree.
    "MediaTag",
    "MediaAssetTag",
    "TagNode",
    "activities_by_kind",
    "TagIndex",
    # #1472: the picker's offer.
    "PICK_PAGE_SIZE",
    "PICKABLE_KINDS",
    "PickGroup",
    "PickItem",
    "PickOptions",
    "media_url",
    "offered_by_picker",
    "pick_options",
    "tag_index",
    "tag_tree",
    "tag_paths",
    "tag_subtree_ids",
    "list_media_with_tag",
    "tags_of_assets",
    "create_tag",
    "rename_tag",
    "move_tag",
    "delete_tag",
    "tag_asset",
    "untag_asset",
    "set_asset_tags",
    "MediaFout",
    "VALID_KINDS",
    "UPLOADABLE_KINDS",
    "DESIGN_KINDS",
    "DESIGN_IMAGE_KIND",
    "DESIGN_RENDER_KIND",
    "DOCUMENT_KINDS",
    "PAGE_IMAGE_KIND",
    "SVG_CONTENT_TYPE",
    "add_document",
    "tenant_logo",
    "activity_ids_with_media",
    "activity_image_path",
    "activity_photo_covers",
    "delete_media",
    "list_activity_photos",
    "list_media",
    "move_media",
    "update_media",
    "upload_media",
    "thumb_counts",
    "thumbs_of_visitor",
    "toggle_thumb",
    "MediaAsset",
    "MediaKind",
    "MediaThumbsUp",
    "MEDIA_KIND",
    "as_media_kind",
    "EXTRACTABLE_KINDS",
    "extract_document_text",
    "delete_activity_poster",
    "delete_component_info",
    "reextract_text",
    "replace_activity_poster",
    "store_activity_poster",
    "store_uploads",
    "remove_media",
    "replace_component_info",
    "update_media_extracted_text",
    # CR-15 #1471: where a picture is used, and the refusal to delete it then.
    "MediaInUse",
    "MediaUse",
    "uses_by_asset",
    "uses_of",
]


# ── Onderaan, en dat is opzet ────────────────────────────────────────────────
# `media/service.py` raakt via `upload_media` het activities-domein aan, en dat
# leidt uiteindelijk terug naar deze facade. Staat de import bovenaan, dan is
# `EXTRACTABLE_KINDS` nog niet gebonden wanneer de keten terugkomt. Onderaan wel.
from app.domains.media.service import (  # noqa: F401
    DESIGN_IMAGE_KIND,
    DESIGN_KINDS,
    DESIGN_RENDER_KIND,
    DOCUMENT_KINDS,
    PAGE_IMAGE_KIND,
    PICK_PAGE_SIZE,
    PICKABLE_KINDS,
    UPLOADABLE_KINDS,
    VALID_KINDS,
    MediaFout,
    MediaInUse,
    MediaUse,
    PickGroup,
    PickItem,
    PickOptions,
    TagIndex,
    TagNode,
    activities_by_kind,
    activity_ids_with_media,
    activity_image_path,
    activity_photo_covers,
    add_document,
    create_tag,
    delete_activity_poster,
    delete_component_info,
    delete_media,
    delete_tag,
    list_activity_photos,
    list_media,
    list_media_with_tag,
    media_url,
    move_media,
    move_tag,
    offered_by_picker,
    pick_options,
    reextract_text,
    remove_media,
    rename_tag,
    replace_activity_poster,
    replace_component_info,
    set_asset_tags,
    store_activity_poster,
    store_uploads,
    tag_asset,
    tag_index,
    tag_paths,
    tag_subtree_ids,
    tag_tree,
    tags_of_assets,
    tenant_logo,
    thumb_counts,
    thumbs_of_visitor,
    toggle_thumb,
    untag_asset,
    update_media,
    upload_media,
    uses_by_asset,
    uses_of,
)
