"""Bevroren lijsten van de overtreders die er vandaag zijn (CR-12 §B9.3).

Het #780-patroon: zolang een telling niet nul is, is de poort een **ratel**. De
overtreders van vandaag staan hier; een nieuwe is rood, en een die uit de code
verdwijnt moet hier ook weg of de test is rood. Zo kan de lijst alleen krimpen,
en is "nog niet opgeruimd" iets anders dan "mag".

Fase 5 van CR-12 verwijdert elk van deze verzamelingen samen met de
uitzonderingslogica in de poort: een ratel op nul wordt een harde poort.

**Waarom hier geen regelnummers staan.** §B9.3 laat `file:line` of `file:name`
toe. Regelnummers verschuiven bij de eerste niet-verwante bewerking bovenaan het
bestand, en dan is de ratel elke dag rood om een reden die niets met codes te
maken heeft — een poort die om de verkeerde reden rood staat, wordt uitgezet.
Daarom is elke sleutel hier stabiel: een kolomnaam, een klassenaam, of de
vergelijking zelf. De **melding** noemt wél `file:line`, want daar moet de lezer
naartoe.
"""

#: Kolommen die een vocabularium opslaan maar (nog) geen FK naar een codetabel
#: hebben. Sleutel: `schema.tabel.kolom`. Het heuristische net van §B9.3 —
#: uitdrukkelijk een net en geen bewijs: een kolom die `categorie` heet ontsnapt
#: eraan tot iemand haar registreert.
FK_ONTBREEKT: frozenset[str] = frozenset({
    'activities.activity_sub_registrations.registration_type_code',
    'activities.registrations.payment_method',
    'activities.registrations.registration_type',
    'ai.ai_call_log.provider',
    'ai.ai_call_log.status',
    'auth.login_tokens.otp_code',
    'auth.user_roles.role_code',
    'designstudio.design_highlights.icon_code',
    'designstudio.design_renditions.layout_code',
    'designstudio.design_renditions.size_code',
    'designstudio.design_renditions.variant',
    'designstudio.designs.duo_code',
    'designstudio.designs.preset',
    'designstudio.designs.status',
    'designstudio.image_generations.status',
    'designstudio.image_generations.style',
    'form.form_fields.field_type',
    'form.forms.status',
    'mail.email_log.email_type',
    'mail.email_log.status',
    'mdm.external_numbers.source',
    'mdm.organizations.org_type',
    'media.media_assets.content_type',
    'media.media_assets.kind',
    'media.media_assets.thumb_content_type',
    'meetings.meeting_attendances.status',
    'meetings.meeting_files.content_type',
    'meetings.meeting_files.purpose',
    'meetings.meeting_sections.kind',
    'newsletter.deliveries.kind',
    'newsletter.deliveries.status',
    'newsletter.drafting_messages.role',
    'newsletter.newsletters.audience',
    'newsletter.newsletters.reply_to_mode',
    'newsletter.newsletters.status',
    'newsletter.subscribers.source',
    'newsletter.subscribers.status',
    'payment.gateway_payments.provider',
    'payment.gateway_payments.status',
    'payment.payment_records.method',
    'payment.payment_records.payable_type',
    'payment.payment_records.status',
    'payment.payment_records.type',
    'public.kernel_jobs.status',
    'reporting.export_log.kind',
    'workflow.workflow_instances.definition_code',
    'workflow.workflow_instances.status',
    'workflow.workflow_instances.subject_type',
    'workflow.workflow_tasks.kind',
    'workflow.workflow_tasks.required_role',
    'workflow.workflow_tasks.status',
    'workflow.workflow_tasks.subject_type',
})

#: `Enum`-klassen onder `app/` die in geen enkele `CodeList` zitten en ook niet
#: als `TechnicalEnum`/`ExternalVocabulary` gemarkeerd zijn.
#: Sleutel: `pad/naar/bestand.py:KlasseNaam`.
ENUM_ZONDER_LIJST: frozenset[str] = frozenset({
    'app/domains/activities/service.py:RegistrationState',
    'app/domains/mdm/models.py:LegalForm',
    'app/domains/reporting/universe.py:Role',
})

#: Labelwoordenboeken in Python — de vorm die deze change request wegneemt.
#: Sleutel: `pad/naar/bestand.py:NAAM`.
LABELWOORDENBOEKEN: frozenset[str] = frozenset({
    'app/domains/activities/export.py:_METHOD_LABELS',
    'app/domains/activities/export.py:_RECORD_METHOD_LABELS',
    'app/domains/activities/export.py:_RECORD_STATUS_LABELS',
    'app/domains/activities/export.py:_RECORD_TYPE_LABELS',
    'app/domains/audit/changes.py:_OPERATION_LABELS',
    'app/domains/chatbot/admin_ui.py:CAPABILITY_LABELS',
    'app/domains/chatbot/admin_ui.py:STATUS_LABELS',
    'app/domains/chatbot/admin_ui.py:SURFACE_LABELS',
    'app/domains/cms/render.py:PLACEHOLDER_LABELS',
    'app/domains/designstudio/admin_ui.py:CORNER_LABELS',
    'app/domains/designstudio/admin_ui.py:DUO_LABELS',
    'app/domains/designstudio/admin_ui.py:GENERATION_LABELS',
    'app/domains/designstudio/imaging.py:STYLE_LABELS',
    'app/domains/designstudio/service.py:FILE_LAYOUT_LABELS',
    'app/domains/designstudio/service.py:FILE_SIZE_LABELS',
    'app/domains/designstudio/service.py:LAYOUT_LABELS',
    'app/domains/designstudio/service.py:PRESET_LABELS',
    'app/domains/designstudio/service.py:STATUS_LABELS',
    'app/domains/forms/models.py:RATING_LABELS',
    'app/domains/mail/ui.py:_STATUS_LABELS',
    'app/domains/mail/ui.py:_TYPE_LABELS',
    'app/domains/meetings/service.py:SECTION_LABELS',
    'app/domains/newsletter/admin_ui.py:AUDIENCE_LABELS',
    'app/domains/newsletter/admin_ui.py:DELIVERY_LABELS',
    'app/domains/newsletter/admin_ui.py:LETTER_STATUS_LABELS',
    'app/domains/newsletter/admin_ui.py:SOURCE_LABELS',
    'app/domains/newsletter/admin_ui.py:SUBSCRIBER_LABELS',
    'app/domains/reporting/assistant.py:_STATUS_LABEL',
    'app/domains/reporting/engine.py:SYMBOLIC_LABELS',
    'app/domains/workflow/ui.py:CAT_LABELS',
    'app/domains/workflow/ui.py:KIND_LABELS',
    'app/ui/__init__.py:_RELATIE_LABELS',
    'app/ui/organisaties_ui.py:SOORT_LABELS',
})

#: Templates die een code met een letterlijke tekst vergelijken.
#: Sleutel: `pad/naar/template.html:attribuut==waarde`.
TEMPLATE_VERGELIJKINGEN: frozenset[str] = frozenset({
    'app/domains/activities/templates/_aa_rail.html:registration_state==closed',
    'app/domains/activities/templates/_activiteiten_cards.html:registration_state==closed',
    'app/domains/activities/templates/_activiteiten_cards.html:registration_state==open',
    'app/domains/activities/templates/_activiteiten_cards.html:status!=Open',
    'app/domains/activities/templates/activiteit.html:registration_state==closed',
    'app/domains/activities/templates/activiteit.html:registration_state==open',
    'app/domains/activities/templates/activiteit.html:status!=Open',
    'app/domains/forms/templates/_fb_recordkop.html:status==closed',
    'app/domains/forms/templates/_fb_recordkop.html:status==open',
    'app/domains/forms/templates/_fb_resultaten.html:field_type==number',
    'app/domains/forms/templates/_fb_resultaten.html:field_type==rating',
    'app/domains/forms/templates/_formulier_veld.html:field_type==checkbox',
    'app/domains/forms/templates/_formulier_veld.html:field_type==email',
    'app/domains/forms/templates/_formulier_veld.html:field_type==info',
    'app/domains/forms/templates/_formulier_veld.html:field_type==number',
    'app/domains/forms/templates/_formulier_veld.html:field_type==phone',
    'app/domains/forms/templates/_formulier_veld.html:field_type==radio',
    'app/domains/forms/templates/_formulier_veld.html:field_type==rating',
    'app/domains/forms/templates/_formulier_veld.html:field_type==select',
    'app/domains/forms/templates/_formulier_veld.html:field_type==textarea',
    'app/domains/forms/templates/formulier_afdruk.html:field_type==info',
    'app/domains/forms/templates/formulier_afdruk.html:field_type==rating',
    'app/domains/forms/templates/formulier_afdruk.html:field_type==textarea',
    'app/domains/mail/templates/_email_log_lijst.html:status==failed',
    'app/domains/mail/templates/_email_log_lijst.html:status==sent',
    'app/domains/mdm/templates/_leden_persoon_velden.html:relation_type==HOOFDLID',
    'app/domains/media/templates/_me_lijst.html:kind==sponsor',
    'app/domains/meetings/templates/_vg_document.html:kind==CUSTOM',
    'app/domains/meetings/templates/_vg_document.html:kind==IDEAS',
    'app/domains/meetings/templates/_vg_document.html:kind==MEMBERS',
    'app/domains/meetings/templates/_vg_punt.html:kind==activity',
    'app/domains/meetings/templates/_vg_punt.html:kind==member',
    'app/domains/meetings/templates/meeting_pdf.html:kind!=MEMBERS',
    'app/domains/meetings/templates/meeting_pdf.html:kind==MEMBERS',
    'app/domains/membership/templates/gezin_portaal.html:relation_type==HOOFDLID',
    'app/domains/newsletter/templates/_nb_abonnees.html:status!=unsubscribed',
    'app/domains/newsletter/templates/_nb_raakje.html:kind==insert',
    'app/domains/newsletter/templates/_nb_raakje.html:kind==letter',
    'app/domains/newsletter/templates/_nb_raakje.html:kind==replace',
    'app/domains/newsletter/templates/_nb_raakje.html:role==author',
    'app/domains/newsletter/templates/_nb_raakje.html:status==applied',
    'app/domains/newsletter/templates/_nb_raakje.html:status==open',
    'app/domains/payment/templates/_betalingen_lijst.html:method==online',
    'app/domains/payment/templates/_betalingen_lijst.html:payable_type==registration',
    'app/domains/payment/templates/_betalingen_lijst.html:status!=paid',
    'app/domains/payment/templates/_betalingen_lijst.html:status==paid',
    'app/domains/payment/templates/_betalingen_lijst.html:type!=refund',
    'app/domains/payment/templates/_betalingen_lijst.html:type==refund',
    'app/domains/workflow/templates/_werkbank_detail.html:status==done',
    'app/domains/workflow/templates/_werkbank_lijst.html:status==done',
    'app/ui/templates/_org_kaarten.html:org_type==ACCOUNT',
    'app/ui/templates/_tn_kaarten.html:org_type==PLATFORM',
})

#: Losse stringvergelijkingen op een vocabulariumattribuut in `.py`.
#: Sleutel: `pad/naar/bestand.py:attribuut==waarde`.
LOSSE_STRINGS: frozenset[str] = frozenset({
    'app/domains/activities/admin_ui.py:status==Open',
    'app/domains/activities/export.py:method==online',
    'app/domains/activities/export.py:type==refund',
    'app/domains/activities/models.py:content_type==application/pdf',
    'app/domains/activities/models.py:kind==component_info',
    'app/domains/activities/router.py:contact_type_code==EMAIL',
    'app/domains/activities/router.py:payment_method==ONLINE',
    'app/domains/activities/ui.py:contact_type_code==EMAIL',
    'app/domains/activities/ui.py:contact_type_code==MOBILE',
    'app/domains/audit/changes.py:contact_type_code==EMAIL',
    'app/domains/audit/changes.py:relation_type==HOOFDLID',
    'app/domains/auth/admin_ui.py:role_code==OPERATOR',
    'app/domains/auth/member_identity.py:contact_type_code==EMAIL',
    'app/domains/auth/member_identity.py:relation_type==HOOFDLID',
    'app/domains/auth/router.py:contact_type_code in MOBILE',
    'app/domains/auth/router.py:contact_type_code in PHONE',
    'app/domains/auth/router.py:contact_type_code==EMAIL',
    'app/domains/auth/users.py:role_code==OPERATOR',
    'app/domains/chatbot/info_service.py:content_type==application/pdf',
    'app/domains/chatbot/info_service.py:kind==activity_poster',
    'app/domains/chatbot/info_service.py:kind==component_info',
    'app/domains/chatbot/router.py:role==user',
    'app/domains/designstudio/admin_ui.py:status==requested',
    'app/domains/designstudio/blocks.py:preset!=tekst',
    'app/domains/designstudio/blocks.py:preset==eenvoudig',
    'app/domains/designstudio/blocks.py:preset==tekst',
    'app/domains/designstudio/service.py:content_type==image/svg+xml',
    'app/domains/designstudio/service.py:status==fetched',
    'app/domains/forms/export.py:field_type!=info',
    'app/domains/forms/router.py:status!=open',
    'app/domains/forms/router.py:status==draft',
    'app/domains/forms/service.py:field_type in radio',
    'app/domains/forms/service.py:field_type in select',
    'app/domains/forms/service.py:field_type not in radio',
    'app/domains/forms/service.py:field_type not in select',
    'app/domains/forms/service.py:field_type==info',
    'app/domains/forms/service.py:status!=open',
    'app/domains/forms/ui.py:field_type in radio',
    'app/domains/forms/ui.py:field_type in select',
    'app/domains/forms/ui.py:field_type!=info',
    'app/domains/forms/ui.py:field_type==checkbox',
    'app/domains/forms/ui.py:field_type==info',
    'app/domains/forms/ui.py:field_type==number',
    'app/domains/forms/ui.py:field_type==rating',
    'app/domains/mail/handlers.py:status==sent',
    'app/domains/mail/service.py:payment_method!=FREE',
    'app/domains/mdm/service.py:contact_type_code==EMAIL',
    'app/domains/mdm/tenant_lookup.py:org_type==PLATFORM',
    'app/domains/mdm/tenant_lookup.py:org_type==UNIT',
    'app/domains/mdm/tenant_service.py:org_type==ACCOUNT',
    'app/domains/mdm/tenant_service.py:org_type==PLATFORM',
    'app/domains/mdm/tenant_service.py:org_type==UNIT',
    'app/domains/media/images.py:mode in LA',
    'app/domains/media/images.py:mode in RGBA',
    'app/domains/media/images.py:mode!=RGB',
    'app/domains/media/images.py:mode!=RGBA',
    'app/domains/media/images.py:mode==P',
    'app/domains/media/pdf.py:mode!=RGB',
    'app/domains/media/router.py:kind==activity_photo',
    'app/domains/media/router.py:kind==sponsor',
    'app/domains/media/service.py:content_type==application/pdf',
    'app/domains/media/service.py:kind==activity_photo',
    'app/domains/media/service.py:kind==activity_poster',
    'app/domains/media/service.py:kind==component_info',
    'app/domains/media/service.py:kind==tenant_logo',
    'app/domains/meetings/service.py:kind==member',
    'app/domains/membership/household_router.py:contact_type_code==EMAIL',
    'app/domains/membership/household_service.py:contact_type_code==EMAIL',
    'app/domains/membership/household_service.py:contact_type_code==MOBILE',
    'app/domains/membership/household_service.py:contact_type_code==PHONE',
    'app/domains/membership/household_service.py:relation_type==HOOFDLID',
    'app/domains/membership/register_router.py:contact_type_code==EMAIL',
    'app/domains/membership/register_router.py:payable_type==membership',
    'app/domains/membership/register_router.py:payment_method==online',
    'app/domains/membership/register_router.py:relation_type==HOOFDLID',
    'app/domains/membership/register_router.py:status in paid',
    'app/domains/membership/register_router.py:status in pending',
    'app/domains/membership/schemas_family.py:relation_type==HOOFDLID',
    'app/domains/membership/service.py:payable_type==membership',
    'app/domains/membership/ui.py:method==transfer',
    'app/domains/newsletter/drafting.py:status!=draft',
    'app/domains/payment/exports.py:payable_type==membership',
    'app/domains/payment/exports.py:payable_type==registration',
    'app/domains/payment/exports.py:relation_type==HOOFDLID',
    'app/domains/payment/service.py:contact_type_code==EMAIL',
    'app/domains/payment/service.py:method in cash',
    'app/domains/payment/service.py:method in transfer',
    'app/domains/payment/service.py:method==online',
    'app/domains/payment/service.py:payable_type!=membership',
    'app/domains/payment/service.py:payable_type!=registration',
    'app/domains/payment/service.py:payable_type==membership',
    'app/domains/payment/service.py:payable_type==registration',
    'app/domains/payment/service.py:relation_type==HOOFDLID',
    'app/domains/payment/service.py:status==paid',
    'app/domains/payment/service.py:status==pending',
    'app/domains/payment/service.py:type!=charge',
    'app/domains/payment/service.py:type!=refund',
    'app/domains/payment/service.py:type==charge',
    'app/domains/payment/service.py:type==refund',
    'app/domains/payment/status_router.py:method!=online',
    'app/domains/payment/status_router.py:method==online',
    'app/domains/payment/status_router.py:status==paid',
    'app/domains/payment/ui.py:method==GET',
    'app/domains/payment/ui.py:type!=refund',
    'app/domains/payment/ui.py:type==refund',
    'app/domains/reporting/admin_ui.py:layout==pivot',
    'app/domains/reporting/chart.py:format==money',
    'app/domains/reporting/engine.py:layout==detail',
    'app/domains/reporting/exports.py:layout!=detail',
    'app/domains/reporting/pivot.py:layout!=pivot',
    'app/domains/workflow/api.py:status!=done',
    'app/domains/workflow/api.py:status==done',
    'app/domains/workflow/api.py:status==open',
    'app/domains/workflow/handlers.py:status!=paid',
    'app/domains/workflow/handlers.py:status==failed',
    'app/domains/workflow/handlers.py:status==paid',
    'app/domains/workflow/handlers.py:status==pending',
    'app/domains/workflow/handlers.py:status==sent',
    'app/domains/workflow/handlers.py:type==refund',
    'app/domains/workflow/ui.py:subject_type==email_log',
    'app/domains/workflow/ui.py:subject_type==form_submission',
    'app/domains/workflow/ui.py:subject_type==kernel_job',
    'app/domains/workflow/ui.py:subject_type==payment_record',
    'app/kernel/jobs.py:status==pending',
    'app/schemas/chat.py:role!=user',
    'app/ui/__init__.py:kind==sponsor',
    'app/ui/tenants_ui.py:org_type==PLATFORM',
})
