"""The frozen offenders of the CR-13 gate (`tests/test_rules_gate.py`, §B9.3).

**A burn-down, not an exemption list** (§B9.4). Phase 0 froze today's offenders
per gate; every later phase removes the entries of the domains it migrates and
makes the gate hard for them; phase 4 deletes this file. An entry may only
disappear — the gate turns red on a new offender, and on an entry that no longer
occurs.

**Keys carry no line numbers:** they would shift on the first unrelated edit, and
a gate that turns red for the wrong reason gets switched off. Each key names the
thing it is about — `file::function`, `package:piece`, `METHOD path` — so the
commit that changes the type of that thing can find and settle its entries in
the same commit (§B9.3, the #1268 lesson).

Measured by the collectors themselves on `master` of 28 September 2026 (after
#781), not written by hand.
"""

# Two helpers in activities/models.py that open a session through object_session to
# find an uploaded asset. Phase 1 moves them to the service (the Registration aggregate).
SESSION_ON_ENTITY: frozenset[str] = frozenset(
    {
        "domains/activities/models.py::ActivitySubRegistration._info_asset",
        "domains/activities/models.py::_single_asset",
    }
)


# Phase 0b gave every domain with a single-domain test its tests/; audit, designstudio
# and newsletter have none yet — their tests walk through other domains too, so they
# live in tests/integration/. audit, stt, cms, membership and reporting lack a further
# piece. Phase 4 decides audit and stt (give them the shape, or move them — §B4.5).
MODULE_SHAPE: frozenset[str] = frozenset(
    {
        "audit:CONTRACT.md",
        "audit:codes.py",
        "audit:models.py",
        "audit:tests/",
        "cms:codes.py",
        "designstudio:tests/",
        "membership:codes.py",
        "newsletter:tests/",
        "reporting:CONTRACT.md",
        "stt:CONTRACT.md",
        "stt:api.py",
        "stt:codes.py",
        "stt:models.py",
    }
)


# The one event handler that commits, through _dispatch → _send → _log_email.
# Phase 4 turns it into a job enqueuer (§B4.1). Any other handler that commits is red.
COMMIT_IN_HANDLER: frozenset[str] = frozenset(
    {
        "domains/mail/handlers.py::on_mail_requested",
    }
)


# The same handler, sending over SMTP inside the transaction. Phase 4.
NETWORK_IN_HANDLER: frozenset[str] = frozenset(
    {
        "domains/mail/handlers.py::on_mail_requested",
    }
)


# Every /api/v1 route (method × path) as of 28 September 2026: none is named
# under ## Callers in a CONTRACT.md yet. Phase 4 names each remaining route or removes
# it (R14), measured in the repository and in the PROD access log.
JSON_ROUTE_WITHOUT_CALLER: frozenset[str] = frozenset(
    {
        "DELETE /api/v1/activities/{activity_id}",
        "DELETE /api/v1/activities/{activity_id}/components/{component_id}",
        "DELETE /api/v1/activities/{activity_id}/components/{component_id}/products/{product_id}",
        "DELETE /api/v1/activities/{activity_id}/dates/{date_id}",
        "DELETE /api/v1/activities/{activity_id}/registrations/{registration_id}",
        "DELETE /api/v1/activities/{activity_id}/registrations/{registration_id}/items/{item_id}",
        "DELETE /api/v1/admin/activities/{activity_id}/poster",
        "DELETE /api/v1/admin/chatbot-info/{row_id}",
        "DELETE /api/v1/admin/components/{component_id}/info",
        "DELETE /api/v1/admin/email-log/{log_id}",
        "DELETE /api/v1/admin/media/{asset_id}",
        "DELETE /api/v1/auth/api-keys/{key_id}",
        "DELETE /api/v1/families/{family_id}",
        "DELETE /api/v1/forms/{form_id}",
        "DELETE /api/v1/forms/{form_id}/submissions/{submission_id}",
        "DELETE /api/v1/member/household/persons/{person_id}",
        "DELETE /api/v1/member/household/persons/{person_id}/emails/{contact_id}",
        "DELETE /api/v1/memberships/{membership_id}",
        "DELETE /api/v1/pages/{page_id}",
        "DELETE /api/v1/payment-status/records/{record_id}",
        "DELETE /api/v1/persons/{person_id}",
        "DELETE /api/v1/users/{user_id}",
        "GET /api/v1/activities",
        "GET /api/v1/activities/{activity_id}/components/{component_id}/export",
        "GET /api/v1/activities/{activity_id}/photos",
        "GET /api/v1/activities/{activity_id}/public-registrations",
        "GET /api/v1/activities/{activity_id}/registrations",
        "GET /api/v1/admin/changes",
        "GET /api/v1/admin/chatbot-info",
        "GET /api/v1/admin/email-log",
        "GET /api/v1/admin/media",
        "GET /api/v1/admin/member-changes",
        "GET /api/v1/admin/member-changes/export",
        "GET /api/v1/admin/pages",
        "GET /api/v1/admin/stats",
        "GET /api/v1/admin/system-info",
        "GET /api/v1/auth/api-keys",
        "GET /api/v1/auth/me",
        "GET /api/v1/auth/member/me",
        "GET /api/v1/auth/verify-login",
        "GET /api/v1/blocks/{slug}",
        "GET /api/v1/cms/placeholders",
        "GET /api/v1/families",
        "GET /api/v1/families/{family_id}",
        "GET /api/v1/forms",
        "GET /api/v1/forms/by-token/{share_token}",
        "GET /api/v1/forms/edit/{edit_token}",
        "GET /api/v1/forms/{form_id}",
        "GET /api/v1/forms/{form_id}/export",
        "GET /api/v1/forms/{form_id}/results",
        "GET /api/v1/forms/{form_id}/submissions",
        "GET /api/v1/media/activity-photos/availability",
        "GET /api/v1/media/activity-photos/covers",
        "GET /api/v1/media/{asset_id}",
        "GET /api/v1/media/{asset_id}/thumb",
        "GET /api/v1/member/household",
        "GET /api/v1/members",
        "GET /api/v1/members/{member_id}",
        "GET /api/v1/memberships",
        "GET /api/v1/pages",
        "GET /api/v1/pages/{slug}",
        "GET /api/v1/payment-status/records",
        "GET /api/v1/payment-status/records/export",
        "GET /api/v1/payment-status/records/{payable_type}/{payable_id}",
        "GET /api/v1/payment-status/registrations/{registration_id}/balance",
        "GET /api/v1/persons",
        "GET /api/v1/postal-codes",
        "GET /api/v1/sponsors",
        "GET /api/v1/users",
        "PATCH /api/v1/activities/{activity_id}/registrations/{registration_id}",
        "PATCH /api/v1/activities/{activity_id}/registrations/{registration_id}/items/{item_id}",
        "PATCH /api/v1/admin/chatbot-info/{row_id}",
        "PATCH /api/v1/admin/media/{asset_id}",
        "PATCH /api/v1/payment-status/records/{record_id}",
        "POST /api/v1/activities",
        "POST /api/v1/activities/{activity_id}/components",
        "POST /api/v1/activities/{activity_id}/components/{component_id}/products",
        "POST /api/v1/activities/{activity_id}/dates",
        "POST /api/v1/activities/{activity_id}/register",
        "POST /api/v1/activities/{activity_id}/registrations/{registration_id}/items",
        "POST /api/v1/admin/activities/{activity_id}/poster",
        "POST /api/v1/admin/chatbot-info/notes",
        "POST /api/v1/admin/components/{component_id}/info",
        "POST /api/v1/admin/media",
        "POST /api/v1/admin/media/{asset_id}/extract",
        "POST /api/v1/admin/member-import/commit",
        "POST /api/v1/admin/member-import/preview",
        "POST /api/v1/auth/api-keys",
        "POST /api/v1/auth/request-login",
        "POST /api/v1/auth/verify-otp",
        "POST /api/v1/chat",
        "POST /api/v1/families",
        "POST /api/v1/families/{family_id}/memberships",
        "POST /api/v1/families/{family_id}/persons",
        "POST /api/v1/forms",
        "POST /api/v1/forms/by-token/{share_token}/submit",
        "POST /api/v1/member/household/persons",
        "POST /api/v1/member/household/persons/{person_id}/emails",
        "POST /api/v1/member/household/persons/{person_id}/emails/rows",
        "POST /api/v1/member/household/persons/{person_id}/emails/{contact_id}/primary",
        "POST /api/v1/member/household/renew-membership",
        "POST /api/v1/members",
        "POST /api/v1/members/{member_id}/memberships",
        "POST /api/v1/pages",
        "POST /api/v1/payment-gateway/webhooks/mollie",
        "POST /api/v1/payment-gateway/webhooks/stub",
        "POST /api/v1/payment-status/records/{record_id}/refresh",
        "POST /api/v1/payment-status/records/{record_id}/refund",
        "POST /api/v1/users",
        "PUT /api/v1/activities/{activity_id}",
        "PUT /api/v1/activities/{activity_id}/components/{component_id}",
        "PUT /api/v1/activities/{activity_id}/components/{component_id}/products/{product_id}",
        "PUT /api/v1/activities/{activity_id}/dates/{date_id}",
        "PUT /api/v1/admin/chatbot-info/cms/{page_id}",
        "PUT /api/v1/admin/chatbot-info/media/{asset_id}",
        "PUT /api/v1/families/{family_id}/board-member",
        "PUT /api/v1/forms/edit/{edit_token}",
        "PUT /api/v1/forms/{form_id}",
        "PUT /api/v1/member/household/persons/{person_id}",
        "PUT /api/v1/pages/{page_id}",
        "PUT /api/v1/persons/{person_id}",
        "PUT /api/v1/persons/{person_id}/address",
        "PUT /api/v1/persons/{person_id}/contacts",
        "PUT /api/v1/users/{user_id}",
    }
)


# Every Dutch identifier as of 29 September 2026, measured by the word list in
# test_rules_gate.py (#780): 280 def/class names, 148 test file names, 7 migration
# names, 2 module names, no model column. Not renamed (`CLAUDE.md`, *Code language*):
# an entry leaves when its code is rewritten for another reason. A false positive is
# fixed in the word list, never here.
DUTCH_IDENTIFIERS: frozenset[str] = frozenset(
    {
        "config.py::_leeg_is_niet_gezet",
        "domains/activities/admin_ui.py::_datum_of_none",
        "domains/activities/admin_ui.py::_lijst_ctx",
        "domains/activities/admin_ui.py::_verplaats",
        "domains/activities/admin_ui.py::activiteit_aanmaken",
        "domains/activities/admin_ui.py::activiteit_bijwerken",
        "domains/activities/admin_ui.py::activiteit_inschrijvingen_tab",
        "domains/activities/admin_ui.py::activiteit_nieuw",
        "domains/activities/admin_ui.py::activiteit_verwijderen",
        "domains/activities/admin_ui.py::admin_activiteit_detail",
        "domains/activities/admin_ui.py::admin_activiteiten",
        "domains/activities/admin_ui.py::affiche_verwijderen",
        "domains/activities/admin_ui.py::datum_bijwerken",
        "domains/activities/admin_ui.py::datum_toevoegen",
        "domains/activities/admin_ui.py::datum_verwijderen",
        "domains/activities/admin_ui.py::inschrijving_detail",
        "domains/activities/admin_ui.py::inschrijving_nieuw",
        "domains/activities/admin_ui.py::inschrijving_nieuw_opslaan",
        "domains/activities/admin_ui.py::inschrijving_nieuw_prijzen",
        "domains/activities/admin_ui.py::inschrijving_nieuw_totaal",
        "domains/activities/admin_ui.py::inschrijving_opmerking",
        "domains/activities/admin_ui.py::inschrijving_opslaan",
        "domains/activities/admin_ui.py::inschrijving_pagina",
        "domains/activities/admin_ui.py::inschrijving_regel_bijwerken",
        "domains/activities/admin_ui.py::inschrijving_regel_toevoegen",
        "domains/activities/admin_ui.py::inschrijving_regel_verwijderen",
        "domains/activities/admin_ui.py::inschrijving_totaal",
        "domains/activities/admin_ui.py::inschrijving_verwijderen",
        "domains/activities/admin_ui.py::onderdeel_bijwerken",
        "domains/activities/admin_ui.py::onderdeel_export",
        "domains/activities/admin_ui.py::onderdeel_info_uploaden",
        "domains/activities/admin_ui.py::onderdeel_info_verwijderen",
        "domains/activities/admin_ui.py::onderdeel_toevoegen",
        "domains/activities/admin_ui.py::onderdeel_verplaatsen",
        "domains/activities/admin_ui.py::onderdeel_verwijderen",
        "domains/activities/admin_ui.py::organisator_bijwerken",
        "domains/activities/admin_ui.py::organisator_toevoegen",
        "domains/activities/admin_ui.py::organisator_verwijderen",
        "domains/activities/admin_ui.py::organisatoren_zoeken",
        "domains/activities/admin_ui.py::product_bijwerken",
        "domains/activities/admin_ui.py::product_toevoegen",
        "domains/activities/admin_ui.py::product_verplaatsen",
        "domains/activities/admin_ui.py::product_verwijderen",
        "domains/activities/router.py::_inschrijver",
        "domains/activities/service.py::_controleer_afrekening",
        "domains/activities/service.py::_controleer_slug",
        "domains/activities/service.py::_datum",
        "domains/activities/service.py::_ontbreekt",
        "domains/activities/service.py::_regel",
        "domains/activities/service.py::controleer_bestelproduct",
        "domains/activities/service.py::controleer_inschrijfvelden",
        "domains/activities/service.py::inschrijving_kop_ctx",
        "domains/activities/service.py::inschrijving_tabs",
        "domains/activities/service.py::sorteer_inschrijvingen",
        "domains/activities/totals.py::_betaalbaar",
        "domains/activities/ui.py::_lijst_ctx",
        "domains/activities/ui.py::activiteit_deeplink",
        "domains/activities/ui.py::activiteiten_page",
        "domains/activities/ui.py::inschrijf_form",
        "domains/activities/ui.py::inschrijf_submit",
        "domains/activities/ui.py::inschrijf_totaal",
        "domains/activities/viewmodels.py::AdminActiviteitInschrijvingenView",
        "domains/activities/viewmodels.py::AdminActiviteitenView",
        "domains/activities/viewmodels.py::AdminInschrijvingView",
        "domains/auth/admin_ui.py::_filters_uit",
        "domains/auth/admin_ui.py::_lijst_ctx",
        "domains/auth/admin_ui.py::_lijst_response",
        "domains/auth/admin_ui.py::_platform_rollen_uit",
        "domains/auth/admin_ui.py::_werkruimtes",
        "domains/auth/admin_ui.py::admin_gebruikers",
        "domains/auth/admin_ui.py::gebruiker_aanmaken",
        "domains/auth/admin_ui.py::gebruiker_bijwerken",
        "domains/auth/admin_ui.py::gebruiker_nieuw",
        "domains/auth/admin_ui.py::gebruiker_verwijderen",
        "domains/auth/users.py::_actieve_werkruimte",
        "domains/chatbot/seam.py::_alleen_waarden",
        "domains/chatbot/seam.py::_naamscan_tekst",
        "domains/chatbot/ui.py::ai_context_lijst",
        "domains/chatbot/ui.py::notitie_toevoegen",
        "domains/chatbot/ui.py::raakje_vraag",
        "domains/chatbot/ui.py::rij_bewerken",
        "domains/chatbot/ui.py::rij_toggle",
        "domains/chatbot/ui.py::rij_verwijderen",
        "domains/cms/admin_ui.py::_lijst_ctx",
        "domains/cms/admin_ui.py::admin_paginas",
        "domains/cms/admin_ui.py::pagina_aanmaken",
        "domains/cms/admin_ui.py::pagina_bijwerken",
        "domains/cms/admin_ui.py::pagina_detail",
        "domains/cms/admin_ui.py::pagina_nieuw",
        "domains/cms/admin_ui.py::pagina_verplaatsen",
        "domains/cms/admin_ui.py::pagina_verwijderen",
        "domains/cms/admin_ui.py::pagina_voorbeeld",
        "domains/cms/service.py::verplaats_pagina",
        "domains/cms/ui.py::betaling_geannuleerd",
        "domains/cms/ui.py::betaling_succes",
        "domains/cms/ui.py::cms_pagina",
        "domains/forms/admin_ui.py::_bewerk",
        "domains/forms/admin_ui.py::formulier_aanmaken",
        "domains/forms/admin_ui.py::formulier_afdruk",
        "domains/forms/admin_ui.py::formulier_builder",
        "domains/forms/admin_ui.py::formulier_nieuw",
        "domains/forms/admin_ui.py::formulier_verwijderen",
        "domains/forms/admin_ui.py::formulieren_page",
        "domains/forms/admin_ui.py::instellingen_opslaan",
        "domains/forms/admin_ui.py::inzending_verwijderen",
        "domains/forms/admin_ui.py::inzendingen_export",
        "domains/forms/admin_ui.py::inzendingen_tab",
        "domains/forms/admin_ui.py::optie_bewerken",
        "domains/forms/admin_ui.py::optie_toevoegen",
        "domains/forms/admin_ui.py::optie_verplaatsen",
        "domains/forms/admin_ui.py::optie_verwijderen",
        "domains/forms/admin_ui.py::sectie_bewerken",
        "domains/forms/admin_ui.py::sectie_toevoegen",
        "domains/forms/admin_ui.py::sectie_verplaatsen",
        "domains/forms/admin_ui.py::sectie_verwijderen",
        "domains/forms/admin_ui.py::veld_bewerken",
        "domains/forms/admin_ui.py::veld_toevoegen",
        "domains/forms/admin_ui.py::veld_verplaatsen",
        "domains/forms/admin_ui.py::veld_verwijderen",
        "domains/forms/api.py::submit_bericht",
        "domains/forms/service.py::FormulierFout",
        "domains/forms/service.py::VeldFout",
        "domains/forms/service.py::_sectie_indexen",
        "domains/forms/service.py::_veld",
        "domains/forms/service.py::assert_geen_id_vorm",
        "domains/forms/ui.py::_berichten_form",
        "domains/forms/ui.py::berichten_page",
        "domains/forms/ui.py::berichten_submit",
        "domains/forms/ui.py::formulier_edit_page",
        "domains/forms/ui.py::formulier_edit_submit",
        "domains/forms/ui.py::formulier_op_slug",
        "domains/forms/ui.py::formulier_page",
        "domains/forms/ui.py::formulier_submit",
        "domains/mail/service.py::_regel_html",
        "domains/mail/ui.py::_sorteer_labels",
        "domains/mail/ui.py::_sorteer_url",
        "domains/mail/ui.py::email_log_lijst",
        "domains/mail/ui.py::email_log_verwijderen",
        "domains/mdm/import_service.py::_leeg",
        "domains/mdm/ledenrapport.py::build_bestuurslid_index",
        "domains/mdm/ledenrapport.py::read_ledenrapport",
        "domains/mdm/ledenrapport.py::read_ledenrapport_bytes",
        "domains/mdm/organization_service.py::_bewaar_rekening",
        "domains/mdm/organization_service.py::_organisatie",
        "domains/mdm/organization_service.py::_zet_lijstrij",
        "domains/mdm/service.py::_laatste_datum",
        "domains/mdm/service.py::_persoon_of_404",
        "domains/mdm/service.py::_waarde",
        "domains/mdm/service.py::gezin_tabs",
        "domains/mdm/tenant_service.py::OngeldigeInstelling",
        "domains/mdm/tenant_service.py::TenantFout",
        "domains/mdm/tenant_service.py::_als_bedrag",
        "domains/mdm/tenant_service.py::_als_geheel",
        "domains/mdm/tenant_service.py::_tekst",
        "domains/mdm/ui.py::_fout",
        "domains/mdm/ui.py::_kaart_response",
        "domains/mdm/ui.py::_lidmaatschapsjaren",
        "domains/mdm/ui.py::_lijst_view",
        "domains/mdm/ui.py::adres_opslaan",
        "domains/mdm/ui.py::bestuurslid_zetten",
        "domains/mdm/ui.py::email_rij",
        "domains/mdm/ui.py::email_toevoegen",
        "domains/mdm/ui.py::email_verwijderen",
        "domains/mdm/ui.py::gezin_aanmaken",
        "domains/mdm/ui.py::gezin_detail",
        "domains/mdm/ui.py::gezin_inschrijvingen_tab",
        "domains/mdm/ui.py::gezin_verwijderen",
        "domains/mdm/ui.py::leden_lijst",
        "domains/mdm/ui.py::leden_page",
        "domains/mdm/ui.py::lid_nieuw",
        "domains/mdm/ui.py::lid_nieuw_persoon_rij",
        "domains/mdm/ui.py::lidmaatschap_toevoegen",
        "domains/mdm/ui.py::lidmaatschap_verwijderen",
        "domains/mdm/ui.py::persoon_opslaan",
        "domains/mdm/ui.py::persoon_toevoegen",
        "domains/mdm/ui.py::persoon_verwijderen",
        "domains/mdm/viewmodels.py::LedenView",
        "domains/media/admin_ui.py::_lijst_ctx",
        "domains/media/admin_ui.py::_lijst_response",
        "domains/media/admin_ui.py::media_bijwerken",
        "domains/media/admin_ui.py::media_nieuw",
        "domains/media/admin_ui.py::media_verplaatsen",
        "domains/media/admin_ui.py::media_verwijderen",
        "domains/media/service.py::MediaFout",
        "domains/media/service.py::controleer_link",
        "domains/media/ui.py::activiteit_fotos",
        "domains/membership/household_router.py::_lid_en_doel",
        "domains/membership/household_service.py::_reconcile_geschrapt_lidmaatschap",
        "domains/membership/schemas_family.py::_hoofdlid_contactgegevens_verplicht",
        "domains/membership/service.py::LidgegevensFout",
        "domains/membership/service.py::controleer_geboortedatum_en_geslacht",
        "domains/membership/ui.py::_lopende_vernieuwing",
        "domains/membership/ui.py::gezin_email_hoofdadres",
        "domains/membership/ui.py::gezin_email_rij",
        "domains/membership/ui.py::gezin_email_toevoegen",
        "domains/membership/ui.py::gezin_email_verwijderen",
        "domains/membership/ui.py::gezin_persoon_opslaan",
        "domains/membership/ui.py::gezin_persoon_toevoegen",
        "domains/membership/ui.py::gezin_persoon_verwijderen",
        "domains/membership/ui.py::gezin_portaal",
        "domains/membership/ui.py::gezin_vernieuwen",
        "domains/membership/ui.py::leden_login_redirect",
        "domains/membership/ui.py::leden_login_verify_redirect",
        "domains/membership/ui.py::lid_worden",
        "domains/membership/ui.py::lid_worden_submit",
        "domains/membership/ui.py::persoon_rij",
        "domains/payment/service.py::BetalingFout",
        "domains/payment/service.py::_bedrag",
        "domains/payment/service.py::_ingetypt_bedrag",
        "domains/payment/service.py::_is_lege_vordering",
        "domains/payment/service.py::_nog_uit_te_betalen",
        "domains/payment/service.py::bevestig_betaling",
        "domains/payment/service.py::bewerk_betaling",
        "domains/payment/service.py::registreer_terugbetaling",
        "domains/payment/service.py::saldo_open",
        "domains/payment/service.py::ververs_betaalstatus",
        "domains/payment/service.py::verwijder_betaling",
        "domains/payment/service.py::zet_betaalstatus",
        "domains/payment/ui.py::_activiteit_scope",
        "domains/payment/ui.py::_gezin_scope",
        "domains/payment/ui.py::_kaart",
        "domains/payment/ui.py::_paginakeuze",
        "domains/payment/ui.py::_raakje_op_dit_scherm",
        "domains/payment/ui.py::activiteit_betalingen_tab",
        "domains/payment/ui.py::betaling_bevestigen",
        "domains/payment/ui.py::betaling_bewerken",
        "domains/payment/ui.py::betaling_bijwerken",
        "domains/payment/ui.py::betaling_refund",
        "domains/payment/ui.py::betaling_status",
        "domains/payment/ui.py::betaling_verversen",
        "domains/payment/ui.py::betaling_verwijderen",
        "domains/payment/ui.py::betalingen_export",
        "domains/payment/ui.py::betalingen_lijst",
        "domains/payment/ui.py::betalingen_page",
        "domains/payment/ui.py::gezin_betalingen_tab",
        "domains/payment/ui.py::inschrijving_betalingen_tab",
        "domains/payment/viewmodels.py::BetalingenView",
        "domains/reporting/assistant.py::ScopeNietOverdraagbaar",
        "domains/reporting/assistant.py::_token_voor",
        "domains/reporting/assistant.py::_wat_bestaat_er_wel",
        "domains/reporting/pivot.py::_sleutel",
        "domains/reporting/universe.py::_zet",
        "domains/workflow/ui.py::werkbank_lijst",
        "kernel/geld.py::bedrag",
        "kernel/meetwaarden.py::_datum",
        "kernel/meetwaarden.py::_jaar",
        "kernel/tenant_config.py::_actieve_tenant",
        "kernel/tenant_config.py::_bedrag",
        "kernel/tenant_config.py::_eerste_rekening",
        "kernel/tenant_config.py::_organisatie",
        "kernel/tenant_config.py::_origin_voor",
        "main.py::_StatischeBestanden",
        "migration:044_address_only_on_hoofdlid.py",
        "migration:073_seed_berichten_form.py",
        "migration:074_migrate_ideas_to_berichten.py",
        "migration:092_workflow_subject_id_tekst.py",
        "migration:093_formulier_posities_uniek_per_ouder.py",
        "migration:095_euroteken_voor_de_prijsplaceholder.py",
        "migration:115_reporting_leden_measures.py",
        "module:domains/mdm/ledenrapport.py",
        "module:ui/organisaties_ui.py",
        "test file:test_aanmaken_zonder_modal.py",
        "test file:test_actieve_navigatie.py",
        "test file:test_activiteit_datums_op_eigen_regel.py",
        "test file:test_activiteit_interne_nota.py",
        "test file:test_activiteit_organisatoren.py",
        "test file:test_activiteit_recordpagina.py",
        "test file:test_activiteit_scherm_indeling.py",
        "test file:test_activiteitdetail_verrijking.py",
        "test file:test_activiteiten_editor_623.py",
        "test file:test_activiteiten_keuzelijst.py",
        "test file:test_activiteiten_publiek_ui.py",
        "test file:test_activiteiten_service_crud.py",
        "test file:test_activiteiten_ui.py",
        "test file:test_activiteitkaart_leesmodus.py",
        "test file:test_activiteitspagina_blok_1143.py",
        "test file:test_admin_activiteiten_lijst_ui.py",
        "test file:test_admin_activiteiten_ui.py",
        "test file:test_admin_datum_tijd_ui.py",
        "test file:test_adresbeheer_portaal.py",
        "test file:test_adresbeheer_scherm.py",
        "test file:test_adresrijen_formulier.py",
        "test file:test_assistant_schermscope.py",
        "test file:test_bedrag_op_de_vernieuwing_1241.py",
        "test file:test_beeldmaat_in_de_editor_1230.py",
        "test file:test_bestuur_maakt_inschrijving_aan.py",
        "test file:test_betaalstatus_tonen.py",
        "test file:test_betaling_fout_toont_de_reden.py",
        "test file:test_betalingen_domeinregels.py",
        "test file:test_betalingen_groepsvolgorde.py",
        "test file:test_betalingen_paginering.py",
        "test file:test_betalingen_scope_overleeft_een_mutatie.py",
        "test file:test_betalingen_ui.py",
        "test file:test_betalingen_zicht_overleeft_een_mutatie.py",
        "test file:test_betalingen_zichten.py",
        "test file:test_betalingenvorm_wijzigingen_emaillog.py",
        "test file:test_bevestig_terugbetaald.py",
        "test file:test_bevestiging_gaat_naar_het_ingevulde_adres.py",
        "test file:test_bewerk_knoppenrij_1090.py",
        "test file:test_bewerken_vervangt_de_leesregel.py",
        "test file:test_bijlage_staat_niet_dubbel.py",
        "test file:test_contactblok_uit_de_organisatie.py",
        "test file:test_contextkaart_terugbetaling.py",
        "test file:test_csrf_token_op_elke_pagina.py",
        "test file:test_deelnemerslijst_na_inschrijving.py",
        "test file:test_deploy_rooktest_wacht.py",
        "test file:test_design_system_pagina.py",
        "test file:test_designs_knop_in_de_recordkop.py",
        "test file:test_email_log_sortering.py",
        "test file:test_filterbalk_op_een_regel.py",
        "test file:test_footer_organisatieblok.py",
        "test file:test_form_instellingen_booleans.py",
        "test file:test_forms_lijst_ui.py",
        "test file:test_formulier_anders_tekst.py",
        "test file:test_formulier_json_rondrit.py",
        "test file:test_formulier_leesbare_link.py",
        "test file:test_formulier_opties_ordenen.py",
        "test file:test_formulier_prefill_ui.py",
        "test file:test_formulier_render.py",
        "test file:test_formulier_sprongbestemming.py",
        "test file:test_formulier_volgorde_tiebreaker.py",
        "test file:test_formulier_vraag_verhuizen.py",
        "test file:test_formulier_vraagtype.py",
        "test file:test_formulier_wizard_stap_nul.py",
        "test file:test_formulier_wizard_startstap.py",
        "test file:test_formulier_wizard_ui.py",
        "test file:test_formulierbouwer_iconen.py",
        "test file:test_formulierbouwer_kop.py",
        "test file:test_formulierbouwer_staart.py",
        "test file:test_gate_niet_leeg.py",
        "test file:test_gedeeltelijke_betaling_vereffent_niet.py",
        "test file:test_geen_genest_formulier.py",
        "test file:test_geen_rauwe_codes_op_het_scherm.py",
        "test file:test_gezin_recordpagina.py",
        "test file:test_gezinsportaal_lopende_vernieuwing.py",
        "test file:test_gezinsscherm_deelacties_1111.py",
        "test file:test_golf12_activiteitspagina.py",
        "test file:test_inschrijf_teller.py",
        "test file:test_inschrijfadres_volgt_aanmelding.py",
        "test file:test_inschrijfdatum_per_onderdeel.py",
        "test file:test_inschrijving_contact_corrigeren.py",
        "test file:test_inschrijving_editor_bedragen.py",
        "test file:test_inschrijving_editor_ui.py",
        "test file:test_inschrijving_opslaan_bevestiging.py",
        "test file:test_inschrijving_pagina.py",
        "test file:test_inschrijving_ploegnaam_bewerken.py",
        "test file:test_inschrijving_verplichte_velden.py",
        "test file:test_inschrijvingen_per_onderdeel.py",
        "test file:test_inschrijvingen_per_onderdeel_scherm.py",
        "test file:test_inschrijvingen_sortering.py",
        "test file:test_leden_records_lijst_ui.py",
        "test file:test_leden_ui.py",
        "test file:test_leden_zoeken_op_straat.py",
        "test file:test_ledenexport_volgt_de_periode.py",
        "test file:test_ledenimport_extra_adressen.py",
        "test file:test_ledenimport_wist_niet.py",
        "test file:test_ledenportaal.py",
        "test file:test_ledenrapport_parsing.py",
        "test file:test_ledenwijzigingen_sortering.py",
        "test file:test_lid_aanmaken_een_formulier_1110.py",
        "test file:test_lidgegevens_verplicht.py",
        "test file:test_live_aantal_blijft_staan.py",
        "test file:test_live_totaal_inschrijving.py",
        "test file:test_media_design_soorten.py",
        "test file:test_media_upload_soortkeuze.py",
        "test file:test_meerdere_vorderingen.py",
        "test file:test_meta_regel_uit_de_kit.py",
        "test file:test_migratieketen_gate.py",
        "test file:test_naadwachter_leest_waarden_niet_etiketten.py",
        "test file:test_navigatie_oob_alleen_bij_boost.py",
        "test file:test_nieuwsbrief_alle_adressen.py",
        "test file:test_onderdeel_een_opslaan.py",
        "test file:test_onderdeel_toevoegen_bijlage.py",
        "test file:test_opslaan_bevestiging_schermen.py",
        "test file:test_organisatie_lijsten.py",
        "test file:test_organisatie_opslaan_een_transactie.py",
        "test file:test_organisatie_wereldkenmerken.py",
        "test file:test_organisatiescherm.py",
        "test file:test_paginavolgorde.py",
        "test file:test_penningmeester_door_het_scherm.py",
        "test file:test_product_zichtbaar_label_1201.py",
        "test file:test_publieke_formuliervelden.py",
        "test file:test_publieke_lege_toestanden.py",
        "test file:test_raakje_naam_en_icoon_1117.py",
        "test file:test_raakje_noemt_de_activiteit_1126.py",
        "test file:test_records_lijsten_ui.py",
        "test file:test_refund_weergave.py",
        "test file:test_reporting_activiteitverslag.py",
        "test file:test_reporting_leden_measures.py",
        "test file:test_rollen_per_werkruimte.py",
        "test file:test_scherm_velden.py",
        "test file:test_schermafdruk_zonder_omgevingsbanner.py",
        "test file:test_sectievorm_dient_in_1101.py",
        "test file:test_sorteervolgorde_gelijkstand.py",
        "test file:test_statische_versies.py",
        "test file:test_stille_fout_zichtbaar.py",
        "test file:test_sweep_sluit_taken.py",
        "test file:test_tenant_bedragen.py",
        "test file:test_tenant_beheer.py",
        "test file:test_terugbetaling_kaarten.py",
        "test file:test_vergadering_routes.py",
        "test file:test_vergaderingen.py",
        "test file:test_verplicht_sterretje.py",
        "test file:test_vraagtypografie.py",
        "test file:test_werkbank_betaalkaart.py",
        "test file:test_werkbank_doel.py",
        "test file:test_wijzigingen_scherm.py",
        "test file:test_word_lid_email_rows.py",
        "test file:test_zoek_personen.py",
        "ui/__init__.py::_beheer_account",
        "ui/__init__.py::_footer_organisatie",
        "ui/__init__.py::_gezinslabel",
        "ui/__init__.py::_huidige_gebruiker",
        "ui/__init__.py::_maandkort",
        "ui/__init__.py::_werkruimte_naam",
        "ui/__init__.py::statisch",
        "ui/__init__.py::statisch_hash",
        "ui/changes_ui.py::_sleutel",
        "ui/changes_ui.py::_sorteer_labels",
        "ui/changes_ui.py::_sorteer_url",
        "ui/changes_ui.py::admin_ledenwijzigingen",
        "ui/changes_ui.py::ledenwijzigingen_export",
        "ui/changes_ui.py::wijzigingen_ctx",
        "ui/design_system_ui.py::_iconen",
        "ui/organisaties_ui.py::_lijst_ctx",
        "ui/organisaties_ui.py::organisatie_editor",
        "ui/organisaties_ui.py::organisatie_opslaan",
        "ui/organisaties_ui.py::organisaties",
        "ui/system_ui.py::_mijn_werkruimtes",
        "ui/system_ui.py::_toon",
        "ui/system_ui.py::_werkruimte_namen",
        "ui/system_ui.py::admin_werkruimte_wisselen",
        "ui/tenants_ui.py::_lijst_ctx",
        "ui/tenants_ui.py::instellingen_verhuisd",
        "ui/tenants_ui.py::tenant_aanmaken",
        "ui/tenants_ui.py::tenant_nieuw",
        "ui/tenants_ui.py::tenant_opslaan",
    }
)
