"""The change report, recorded (CR-13 phase 4c, #1251 — the audit package leaves).

What the two change screens and the .ods export show comes from four names:
`GROUPS`, `all_changes_since`, `member_changes_since` and
`build_member_changes_ods`. They read the history tables of four owners through
those owners' facades — a report across domains — and move, unchanged, from
`domains/audit/changes.py` to `domains/reporting/changes.py`.

This test writes one history row of every kind (and a second one where the
report shows what changed between two), at fixed moments, and compares what the
three functions give with what they gave before the move: every row of both
lists, and the cells of the spreadsheet. `EXPECTED` was recorded with the module
still in `audit` (9 October 2026) and has not been touched since.

Proven red (9 October 2026): the sort of `member_changes_since` turned around →
the rows come oldest first and the comparison names the first one.
"""

from __future__ import annotations

import io
import re
import zipfile
from datetime import date, datetime, timezone
from decimal import Decimal
from types import SimpleNamespace

import pytest

from app.domains.activities.history import (
    snapshot_activity,
    snapshot_activity_date,
    snapshot_component,
    snapshot_product,
    snapshot_registration_item,
)
from app.domains.audit.api import (
    GROUPS,
    all_changes_since,
    build_member_changes_ods,
    member_changes_since,
)
from app.domains.mdm.api import (
    CONTACT,
    RelationType,
    snapshot_address,
    snapshot_contact_detail,
    snapshot_member,
    snapshot_member_person,
    snapshot_person,
)
from app.domains.membership.api import snapshot_membership
from app.domains.payment.history import snapshot_payment_record

pytestmark = pytest.mark.ui_agnostisch

SINCE = date(2099, 1, 1)  # after every row another test or a seed could have left
ACTOR = "board@example.org"

EXPECTED: dict[str, object] = {
    "groups": ["Leden", "Activiteiten", "Inschrijvingen", "Betalingen"],
    "every change": [
        {
            "recorded_at": "2099-06-01 12:14:00+00:00",
            "group": "Betalingen",
            "entity": "Betaling",
            "entity_id": None,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "payment_manually_confirmed",
            "actor": "board@example.org",
            "summary": "charge €24.00 transfer/paid (registration #886015)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:13:00+00:00",
            "group": "Inschrijvingen",
            "entity": "Bestelregel",
            "entity_id": 886014,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "registration_item_added",
            "actor": "board@example.org",
            "summary": "product #886013 ×3 (inschrijving #886015)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:12:00+00:00",
            "group": "Activiteiten",
            "entity": "Product",
            "entity_id": 886013,
            "operation": "delete",
            "operation_label": "Verwijderd",
            "action": "product_deleted",
            "actor": "board@example.org",
            "summary": "Adult €8.00 (onderdeel #886012)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:11:00+00:00",
            "group": "Activiteiten",
            "entity": "Onderdeel",
            "entity_id": 886012,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "component_updated",
            "actor": "board@example.org",
            "summary": "Evening part (activiteit #886010)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:10:00+00:00",
            "group": "Activiteiten",
            "entity": "Datum",
            "entity_id": 886011,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "activity_date_added",
            "actor": "board@example.org",
            "summary": "2099-03-14–2099-03-15 (activiteit #886010)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:09:00+00:00",
            "group": "Activiteiten",
            "entity": "Activiteit",
            "entity_id": 886010,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "activity_created",
            "actor": "board@example.org",
            "summary": "Quiz night",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:08:00+00:00",
            "group": "Leden",
            "entity": "Lidmaatschap",
            "entity_id": 886007,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "membership_created",
            "actor": "board@example.org",
            "summary": "jaar 2099, actief=True, 2099-01-01–2099-12-31",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:07:00+00:00",
            "group": "Leden",
            "entity": "Contact",
            "entity_id": 886006,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "contact_updated",
            "actor": "board@example.org",
            "summary": "E-mail: an@example.org → anna@example.org",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:06:00+00:00",
            "group": "Leden",
            "entity": "Contact",
            "entity_id": 886006,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "contact_created",
            "actor": "board@example.org",
            "summary": "E-mail: an@example.org — hoofdadres",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:05:00+00:00",
            "group": "Leden",
            "entity": "Adres",
            "entity_id": 886004,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "address_updated",
            "actor": "board@example.org",
            "summary": "Voorbeeldstraat 12 bus B → Andere straat 12 bus B",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:04:00+00:00",
            "group": "Leden",
            "entity": "Adres",
            "entity_id": 886004,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "address_created",
            "actor": "board@example.org",
            "summary": "Voorbeeldstraat 12 bus B",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:03:00+00:00",
            "group": "Leden",
            "entity": "Gezinslid",
            "entity_id": 886003,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "member_person_added",
            "actor": "board@example.org",
            "summary": "In gezin als HOOFDLID",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:02:00+00:00",
            "group": "Leden",
            "entity": "Gezin",
            "entity_id": 886002,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "member_created",
            "actor": "board@example.org",
            "summary": "Gezin",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:01:00+00:00",
            "group": "Leden",
            "entity": "Persoon",
            "entity_id": 886001,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "person_updated",
            "actor": "board@example.org",
            "summary": "An Voorbeeld → Anna Voorbeeld",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:00:00+00:00",
            "group": "Leden",
            "entity": "Persoon",
            "entity_id": 886001,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "person_created",
            "actor": "board@example.org",
            "summary": "An Voorbeeld (geb. 1980-02-29)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
    ],
    "the members' changes": [
        {
            "recorded_at": "2099-06-01 12:08:00+00:00",
            "group": "Leden",
            "entity": "Lidmaatschap",
            "entity_id": 886007,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "membership_created",
            "actor": "board@example.org",
            "summary": "jaar 2099, actief=True, 2099-01-01–2099-12-31",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:07:00+00:00",
            "group": "Leden",
            "entity": "Contact",
            "entity_id": 886006,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "contact_updated",
            "actor": "board@example.org",
            "summary": "E-mail: an@example.org → anna@example.org",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:06:00+00:00",
            "group": "Leden",
            "entity": "Contact",
            "entity_id": 886006,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "contact_created",
            "actor": "board@example.org",
            "summary": "E-mail: an@example.org — hoofdadres",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:05:00+00:00",
            "group": "Leden",
            "entity": "Adres",
            "entity_id": 886004,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "address_updated",
            "actor": "board@example.org",
            "summary": "Voorbeeldstraat 12 bus B → Andere straat 12 bus B",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:04:00+00:00",
            "group": "Leden",
            "entity": "Adres",
            "entity_id": 886004,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "address_created",
            "actor": "board@example.org",
            "summary": "Voorbeeldstraat 12 bus B",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:03:00+00:00",
            "group": "Leden",
            "entity": "Gezinslid",
            "entity_id": 886003,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "member_person_added",
            "actor": "board@example.org",
            "summary": "In gezin als HOOFDLID",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:02:00+00:00",
            "group": "Leden",
            "entity": "Gezin",
            "entity_id": 886002,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "member_created",
            "actor": "board@example.org",
            "summary": "Gezin",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:01:00+00:00",
            "group": "Leden",
            "entity": "Persoon",
            "entity_id": 886001,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "person_updated",
            "actor": "board@example.org",
            "summary": "An Voorbeeld → Anna Voorbeeld",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:00:00+00:00",
            "group": "Leden",
            "entity": "Persoon",
            "entity_id": 886001,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "person_created",
            "actor": "board@example.org",
            "summary": "An Voorbeeld (geb. 1980-02-29)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
    ],
    "the group of activities": [
        {
            "recorded_at": "2099-06-01 12:12:00+00:00",
            "group": "Activiteiten",
            "entity": "Product",
            "entity_id": 886013,
            "operation": "delete",
            "operation_label": "Verwijderd",
            "action": "product_deleted",
            "actor": "board@example.org",
            "summary": "Adult €8.00 (onderdeel #886012)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:11:00+00:00",
            "group": "Activiteiten",
            "entity": "Onderdeel",
            "entity_id": 886012,
            "operation": "update",
            "operation_label": "Gewijzigd",
            "action": "component_updated",
            "actor": "board@example.org",
            "summary": "Evening part (activiteit #886010)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:10:00+00:00",
            "group": "Activiteiten",
            "entity": "Datum",
            "entity_id": 886011,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "activity_date_added",
            "actor": "board@example.org",
            "summary": "2099-03-14–2099-03-15 (activiteit #886010)",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
        {
            "recorded_at": "2099-06-01 12:09:00+00:00",
            "group": "Activiteiten",
            "entity": "Activiteit",
            "entity_id": 886010,
            "operation": "insert",
            "operation_label": "Toegevoegd",
            "action": "activity_created",
            "actor": "board@example.org",
            "summary": "Quiz night",
            "person_name": "",
            "person_external_id": "",
            "head_address": "",
            "head_external_id": "",
        },
    ],
    "one actor": 15,
    "another actor": 0,
    "the spreadsheet": [
        "Tijdstip",
        "Wat",
        "Type",
        "ID",
        "Naam persoon",
        "Adres hoofdlid",
        "Externe ID persoon",
        "Externe ID hoofdlid",
        "Actie",
        "Door",
        "Details",
        "2099-06-01 12:08",
        "Toegevoegd",
        "Lidmaatschap",
        "886007",
        "membership_created",
        "board@example.org",
        "jaar 2099, actief=True, 2099-01-01–2099-12-31",
        "2099-06-01 12:07",
        "Gewijzigd",
        "Contact",
        "886006",
        "contact_updated",
        "board@example.org",
        "E-mail: an@example.org → anna@example.org",
        "2099-06-01 12:06",
        "Toegevoegd",
        "Contact",
        "886006",
        "contact_created",
        "board@example.org",
        "E-mail: an@example.org — hoofdadres",
        "2099-06-01 12:05",
        "Gewijzigd",
        "Adres",
        "886004",
        "address_updated",
        "board@example.org",
        "Voorbeeldstraat 12 bus B → Andere straat 12 bus B",
        "2099-06-01 12:04",
        "Toegevoegd",
        "Adres",
        "886004",
        "address_created",
        "board@example.org",
        "Voorbeeldstraat 12 bus B",
        "2099-06-01 12:03",
        "Toegevoegd",
        "Gezinslid",
        "886003",
        "member_person_added",
        "board@example.org",
        "In gezin als HOOFDLID",
        "2099-06-01 12:02",
        "Toegevoegd",
        "Gezin",
        "886002",
        "member_created",
        "board@example.org",
        "Gezin",
        "2099-06-01 12:01",
        "Gewijzigd",
        "Persoon",
        "886001",
        "person_updated",
        "board@example.org",
        "An Voorbeeld → Anna Voorbeeld",
        "2099-06-01 12:00",
        "Toegevoegd",
        "Persoon",
        "886001",
        "person_created",
        "board@example.org",
        "An Voorbeeld (geb. 1980-02-29)",
    ],
}


def _person(first_name: str) -> SimpleNamespace:
    return SimpleNamespace(
        id=886_001,
        last_name="Voorbeeld",
        first_name=first_name,
        date_of_birth=date(1980, 2, 29),
        gender_code="F",
    )


def _address(street: str) -> SimpleNamespace:
    return SimpleNamespace(
        id=886_004,
        person_id=886_001,
        street=street,
        house_number="12",
        bus_number="B",
        postal_code_id=None,
    )


def _contact(value: str) -> SimpleNamespace:
    return SimpleNamespace(
        id=886_006,
        person_id=886_001,
        contact_type_code=CONTACT.EMAIL,
        value=value,
        is_primary=True,
    )


#: (the snapshot function, its source, operation, action) — in the order the rows are written.
WRITES = [
    (snapshot_person, _person("An"), "insert", "person_created"),
    (snapshot_person, _person("Anna"), "update", "person_updated"),
    (
        snapshot_member,
        SimpleNamespace(id=886_002, board_member_id=None),
        "insert",
        "member_created",
    ),
    (
        snapshot_member_person,
        SimpleNamespace(
            id=886_003,
            member_id=886_002,
            person_id=886_001,
            relation_type=RelationType.PRIMARY_MEMBER,
        ),
        "insert",
        "member_person_added",
    ),
    (snapshot_address, _address("Voorbeeldstraat"), "insert", "address_created"),
    (snapshot_address, _address("Andere straat"), "update", "address_updated"),
    (snapshot_contact_detail, _contact("an@example.org"), "insert", "contact_created"),
    (snapshot_contact_detail, _contact("anna@example.org"), "update", "contact_updated"),
    (
        snapshot_membership,
        SimpleNamespace(
            id=886_007,
            member_id=886_002,
            year=2099,
            is_active=True,
            valid_from=date(2099, 1, 1),
            valid_to=date(2099, 12, 31),
        ),
        "insert",
        "membership_created",
    ),
    (
        snapshot_activity,
        SimpleNamespace(id=886_010, name="Quiz night"),
        "insert",
        "activity_created",
    ),
    (
        snapshot_activity_date,
        SimpleNamespace(
            id=886_011,
            activity_id=886_010,
            start_date=date(2099, 3, 14),
            end_date=date(2099, 3, 15),
        ),
        "insert",
        "activity_date_added",
    ),
    (
        snapshot_component,
        SimpleNamespace(
            id=886_012,
            activity_id=886_010,
            name="Evening part",
            price=Decimal("12.50"),
            member_price=Decimal("10.00"),
        ),
        "update",
        "component_updated",
    ),
    (
        snapshot_product,
        SimpleNamespace(
            id=886_013, component_id=886_012, name="Adult", price=Decimal("8.00"), member_price=None
        ),
        "delete",
        "product_deleted",
    ),
    (
        snapshot_registration_item,
        SimpleNamespace(id=886_014, registration_id=886_015, product_id=886_013, quantity=3),
        "insert",
        "registration_item_added",
    ),
    (
        snapshot_payment_record,
        SimpleNamespace(
            id="00000000-0000-4000-8000-000000000886",
            payable_type="registration",
            payable_id=886_015,
            amount=Decimal("24.00"),
            amount_paid=Decimal("24.00"),
            method="transfer",
            status="paid",
            type="charge",
            refund_of_id=None,
            gateway_payment_id=None,
            note="seen on the statement",
            paid_at=datetime(2099, 1, 2, 9, 0, tzinfo=timezone.utc),
        ),
        "update",
        "payment_manually_confirmed",
    ),
]


def _plain(value):
    """A value as it compares the same on every run and in every process."""
    if isinstance(value, dict):
        return {key: _plain(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(item) for item in value]
    if value is None or isinstance(value, (bool, int, str)):
        return value
    return str(value)


def _cells(ods: bytes) -> list[str]:
    """The text of every cell of the spreadsheet, in order."""
    content = zipfile.ZipFile(io.BytesIO(ods)).read("content.xml").decode("utf-8")
    return re.findall(r"<text:p>(.*?)</text:p>", content)


def test_the_change_report_gives_what_it_gave(db_session):
    db = db_session
    # Each row at its own fixed moment, a minute apart: the order is the report's, not chance's.
    for minute, (function, source, operation, action) in enumerate(WRITES):
        before = set(db.new)
        function(db, source, operation=operation, action=action, source="recording", actor=ACTOR)
        (row,) = set(db.new) - before
        row.recorded_at = datetime(2099, 6, 1, 12, minute, tzinfo=timezone.utc)
    db.flush()

    members = member_changes_since(db, SINCE)
    got = {
        "groups": _plain(GROUPS),
        "every change": _plain(all_changes_since(db, SINCE)),
        "the members' changes": _plain(members),
        "the group of activities": _plain(all_changes_since(db, SINCE, group="Activiteiten")),
        "one actor": len(all_changes_since(db, SINCE, actor=ACTOR)),
        "another actor": len(all_changes_since(db, SINCE, actor="nobody@example.org")),
        "the spreadsheet": _cells(build_member_changes_ods(members)),
    }
    assert got == EXPECTED
