"""Publieke facade van het cms-component (fase 4c, #404; CR-17 #1671)."""

from app.domains.cms import schema  # noqa: F401
from app.domains.cms.models import (  # noqa: F401
    CmsPage,
    CmsPageHistory,
    CmsPageTranslation,
)
from app.domains.cms.render import (  # noqa: F401
    _format_md,
    _format_price,
    render_cms_content,
    render_document,
    sanitize_cms_html,
)
from app.domains.cms.service import (  # noqa: F401
    SITE_BLOCK_SLUGS,
    SlugBestaatAl,
    create_page,
    delete_page,
    draft_differs,
    draft_document,
    draft_states,
    editable_document,
    get_page_by_id,
    get_published_page,
    get_translation,
    is_page,
    list_pages,
    placeholders,
    publish,
    published_document,
    published_home_page,
    published_page,
    published_slugs,
    references_to_media,
    restore,
    save_draft,
    seed_site_blocks,
    update_page,
    verplaats_pagina,
    versions,
)

__all__ = [
    "SlugBestaatAl",
    "create_page",
    "delete_page",
    "verplaats_pagina",
    "get_page_by_id",
    "get_published_page",
    "list_pages",
    "placeholders",
    # CR-15 #1471: which pages show a picture.
    "references_to_media",
    # CR-19 #1478: the blocks a new tenant's site starts with.
    "seed_site_blocks",
    "published_home_page",
    "published_slugs",
    "published_page",
    "is_page",
    "SITE_BLOCK_SLUGS",
    "update_page",
    "CmsPage",
    "CmsPageHistory",
    "CmsPageTranslation",
    "render_cms_content",
    "render_document",
    "sanitize_cms_html",
    # CR-17 fase 1 (#1671): documents — draft, publish, restore, versions.
    "schema",
    "save_draft",
    "publish",
    "restore",
    "versions",
    "draft_document",
    "draft_differs",
    "draft_states",
    "published_document",
    "editable_document",
    "get_translation",
    "_format_md",
    "_format_price",
]
