"""Public facade of the reporting domain (#832, CR-06).

Reporting is the one domain that reads from everywhere and is imported by nobody:
it consumes the `reporting` views, which the migrations of this domain create over
the other domains' tables. The dependency runs one way only, and
`test_import_boundaries.py` keeps it that way without an allowlist entry.

That is also why this facade exports no ORM class: there is nothing to write here.
A report is a selection over views, and the only thing another module ever needs
from this domain is the vocabulary (the universe) and the two entry points that
run it.
"""

from app.domains.reporting.changes import (
    GROUPS,
    all_changes_since,
    build_member_changes_ods,
    member_changes_since,
)
from app.domains.reporting.chart import (  # noqa: F401
    CHART_LAYOUTS,
    SERIES_COLORS,
    Chart,
    ChartData,
    build_chart,
    chart_data,
)
from app.domains.reporting.codes import EXPORT_KIND  # noqa: F401
from app.domains.reporting.engine import (  # noqa: F401
    LAYOUTS,
    MAX_PIVOT_COLUMNS,
    MAX_ROWS,
    SYMBOLIC_LABELS,
    SYMBOLIC_ME,
    SYMBOLIC_THIS_YEAR,
    SYMBOLIC_TODAY,
    SYMBOLIC_VALUES,
    Column,
    Direction,
    Filter,
    Layout,
    Operator,
    QueryPlan,
    Selection,
    SelectionError,
    Sort,
    build_detail_query,
    build_member_count_query,
    build_query,
    population_of,
    selection_from_dict,
    selection_to_dict,
    values_from_fact_sql,
)
from app.domains.reporting.exports import (  # noqa: F401
    build_dataset_ods,
    build_pivot_ods,
    build_report_ods,
    dataset_filename,
    filter_summary,
    report_filename,
)
from app.domains.reporting.models import ExportKind  # noqa: F401
from app.domains.reporting.pivot import (  # noqa: F401
    Pivot,
    PivotRow,
    build_pivot,
    check_column_cap,
)
from app.domains.reporting.service import (  # noqa: F401
    DASHBOARD_TEGELS,
    OFFER_LIMIT,
    Dataset,
    ReportResult,
    SavedReportError,
    TileNumber,
    classes_of,
    copy_report,
    dashboard_numbers,
    dashboard_tile_of,
    delete_report,
    dimension_values,
    fact_columns,
    filter_of_ticks,
    get_saved_report,
    is_personal,
    list_saved_reports,
    load_dataset,
    log_export,
    mark_run,
    may_delete,
    resolve_selection,
    run_selection,
    run_validated,
    save_report,
    selection_of,
    tick_values,
    update_report,
    validate_filter_values,
)
from app.domains.reporting.universe import (  # noqa: F401
    BY_KEY,
    CLASSES,
    DIMENSIONS,
    FACTS,
    HIERARCHIES,
    HIERARCHY_OF,
    JOINS,
    OBJECTS,
    Fact,
    Format,
    ObjectKind,
    Role,
    UniverseObject,
    classes_with_objects,
    joins_for,
    objects_in_pane_order,
)

__all__ = [
    "GROUPS",
    "all_changes_since",
    "build_member_changes_ods",
    "member_changes_since",
    "BY_KEY",
    "CHART_LAYOUTS",
    "CLASSES",
    "DIMENSIONS",
    "FACTS",
    "JOINS",
    "HIERARCHIES",
    "HIERARCHY_OF",
    "LAYOUTS",
    "Layout",
    "SERIES_COLORS",
    "SYMBOLIC_LABELS",
    "SYMBOLIC_ME",
    "SYMBOLIC_THIS_YEAR",
    "SYMBOLIC_TODAY",
    "SYMBOLIC_VALUES",
    "MAX_PIVOT_COLUMNS",
    "MAX_ROWS",
    "OBJECTS",
    "OFFER_LIMIT",
    "Chart",
    "ChartData",
    "Column",
    "Dataset",
    "Direction",
    "Fact",
    "Filter",
    "Format",
    "ObjectKind",
    "Operator",
    "Pivot",
    "PivotRow",
    "QueryPlan",
    "ReportResult",
    "Role",
    "SavedReportError",
    "Selection",
    "SelectionError",
    "Sort",
    "TileNumber",
    "UniverseObject",
    "build_dataset_ods",
    "build_detail_query",
    "build_member_count_query",
    "build_chart",
    "build_pivot",
    "build_pivot_ods",
    "build_query",
    "build_report_ods",
    "chart_data",
    "check_column_cap",
    "classes_of",
    "classes_with_objects",
    "copy_report",
    "DASHBOARD_TEGELS",
    "dashboard_numbers",
    "dashboard_tile_of",
    "dataset_filename",
    "may_delete",
    "delete_report",
    "dimension_values",
    "fact_columns",
    "filter_summary",
    "population_of",
    "values_from_fact_sql",
    "get_saved_report",
    "joins_for",
    "list_saved_reports",
    "load_dataset",
    "is_personal",
    "log_export",
    "mark_run",
    "EXPORT_KIND",
    "ExportKind",
    "objects_in_pane_order",
    "report_filename",
    "filter_of_ticks",
    "tick_values",
    "resolve_selection",
    "run_selection",
    "run_validated",
    "save_report",
    "selection_from_dict",
    "selection_of",
    "selection_to_dict",
    "update_report",
    "validate_filter_values",
]
