"""Public facade of the newsletter component (CR-05, #984).

Other components — and this component's own screens — reach newsletter
functionality only through this module (boundary tests: cross-domain only via
``.api``; UI modules only via ``api.py``). The ORM classes are exported for
other domains' services, never for a screen.
"""
from app.domains.newsletter.models import (  # noqa: F401
    AUDIENCE_BOTH,
    AUDIENCE_MEMBERS,
    AUDIENCE_NON_MEMBERS,
    AUDIENCES,
    DELIVERY_FAILED,
    DELIVERY_MEMBER,
    DELIVERY_QUEUED,
    DELIVERY_SENT,
    DELIVERY_SKIPPED,
    DELIVERY_SUBSCRIBER,
    LETTER_DRAFT,
    LETTER_SENDING,
    LETTER_SENT,
    MESSAGE_AUTHOR,
    MESSAGE_RAAKJE,
    REPLY_TO_ASSOCIATION,
    REPLY_TO_SENDER,
    SOURCE_ADMIN,
    SOURCE_IMPORT,
    SOURCE_PUBLIC_FORM,
    SUBSCRIBER_CONFIRMED,
    SUBSCRIBER_PENDING,
    SUBSCRIBER_UNSUBSCRIBED,
    Delivery,
    DraftingMessage,
    Newsletter,
    Subscriber,
)
from app.domains.newsletter.drafting import (  # noqa: F401
    DraftingError,
    apply as apply_proposal,
    ask as ask_raakje,
    dismiss as dismiss_proposal,
    display as display_proposal,
    get_message as get_drafting_message,
    record as record_turn,
)
from app.domains.newsletter.service import (  # noqa: F401
    SEND_JOB,
    NewsletterError,
    activity_facts,
    activity_block_html,
    activity_card_html,
    expand_blocks,
    activity_line_html,
    add_attachment,
    add_by_admin,
    audience_counts,
    calendar_html,
    closing_html,
    confirm,
    copy_newsletter,
    create_newsletter,
    deliveries_of,
    delete_draft,
    erase,
    expected_days,
    get_newsletter,
    greeting_html,
    insertable_activities,
    list_newsletters,
    list_subscribers,
    member_addresses,
    messages_of,
    preview_import,
    progress_of,
    recipients_for,
    render_mail,
    resubscribe,
    run_import,
    save_settings,
    send_batch,
    send_test,
    set_draft_sources,
    short_date,
    placeholder_refusal,
    start_sending,
    subscribe_public,
    subscriber_by_confirm_token,
    subscriber_by_unsubscribe_token,
    subscriber_counts,
    unsubscribe,
    unfilled_placeholders,
    unsubscribe_by_admin,
    update_draft,
)

__all__ = [
    "AUDIENCE_BOTH", "AUDIENCE_MEMBERS", "AUDIENCE_NON_MEMBERS", "AUDIENCES",
    "DELIVERY_FAILED", "DELIVERY_MEMBER", "DELIVERY_QUEUED", "DELIVERY_SENT",
    "DELIVERY_SKIPPED", "DELIVERY_SUBSCRIBER",
    "LETTER_DRAFT", "LETTER_SENDING", "LETTER_SENT",
    "MESSAGE_AUTHOR", "MESSAGE_RAAKJE", "REPLY_TO_ASSOCIATION", "REPLY_TO_SENDER",
    "SOURCE_ADMIN", "SOURCE_IMPORT", "SOURCE_PUBLIC_FORM",
    "SUBSCRIBER_CONFIRMED", "SUBSCRIBER_PENDING", "SUBSCRIBER_UNSUBSCRIBED",
    "Delivery", "DraftingMessage", "Newsletter", "Subscriber",
    "DraftingError", "apply_proposal", "ask_raakje", "dismiss_proposal",
    "display_proposal", "get_drafting_message", "record_turn",
    "SEND_JOB", "NewsletterError", "activity_facts", "activity_block_html", "activity_card_html", "activity_line_html", "expand_blocks", "add_attachment",
    "add_by_admin", "audience_counts", "calendar_html", "closing_html", "confirm",
    "copy_newsletter", "create_newsletter", "deliveries_of", "delete_draft", "erase",
    "expected_days", "get_newsletter", "greeting_html",
    "insertable_activities", "list_newsletters", "list_subscribers",
    "member_addresses", "messages_of", "preview_import", "progress_of",
    "recipients_for", "render_mail", "resubscribe", "run_import", "save_settings", "send_batch",
    "send_test", "set_draft_sources", "short_date", "start_sending",
    "subscribe_public", "subscriber_by_confirm_token",
    "subscriber_by_unsubscribe_token", "subscriber_counts", "unsubscribe",
    "unsubscribe_by_admin", "update_draft",
    "placeholder_refusal", "unfilled_placeholders",
]
