"""Public facade of the newsletter component (CR-05, #984).

Other components — and this component's own screens — reach newsletter
functionality only through this module (boundary tests: cross-domain only via
``.api``; UI modules only via ``api.py``). The ORM classes are exported for
other domains' services, never for a screen.
"""

from app.domains.newsletter.codes import (  # noqa: F401
    AUDIENCE,
    DELIVERY_KIND,
    DELIVERY_STATUS,
    LETTER_STATUS,
    MESSAGE_ROLE,
    REPLY_TO_MODE,
    SUBSCRIBER_SOURCE,
    SUBSCRIBER_STATUS,
)
from app.domains.newsletter.drafting import (  # noqa: F401
    DraftingError,
)
from app.domains.newsletter.drafting import (
    apply as apply_proposal,
)
from app.domains.newsletter.drafting import (
    ask as ask_raakje,
)
from app.domains.newsletter.drafting import (
    dismiss as dismiss_proposal,
)
from app.domains.newsletter.drafting import (
    display as display_proposal,
)
from app.domains.newsletter.drafting import (
    get_message as get_drafting_message,
)
from app.domains.newsletter.drafting import (
    record as record_turn,
)
from app.domains.newsletter.models import (  # noqa: F401
    Audience,
    Delivery,
    DeliveryKind,
    DeliveryStatus,
    DraftingMessage,
    LetterStatus,
    MessageRole,
    Newsletter,
    ReplyToMode,
    Subscriber,
    SubscriberSource,
    SubscriberStatus,
)
from app.domains.newsletter.service import (  # noqa: F401
    CALENDAR_DEFAULT,
    FEATURED_MAX,
    GROUPS,
    SEND_JOB,
    Choices,
    NewsletterError,
    activity_block_html,
    activity_card_html,
    activity_facts,
    activity_line_html,
    add_attachment,
    add_by_admin,
    audience_counts,
    audience_summary,
    calendar_html,
    choices_of,
    closing_html,
    confirm,
    copy_newsletter,
    create_newsletter,
    default_choices,
    delete_draft,
    deliveries_of,
    draft_subject,
    erase,
    expand_blocks,
    expected_days,
    get_newsletter,
    greeting_html,
    insertable_activities,
    list_newsletters,
    list_subscribers,
    member_addresses,
    messages_of,
    placeholder_refusal,
    plain_text,
    preview_import,
    preview_text_of,
    progress_of,
    recipients_for,
    render_mail,
    render_text,
    reports_since_previous_letter,
    resubscribe,
    run_import,
    save_settings,
    send_batch,
    send_test,
    set_choice,
    set_draft_sources,
    short_date,
    start_sending,
    subscribe_public,
    subscriber_by_confirm_token,
    subscriber_by_unsubscribe_token,
    subscriber_counts,
    unfilled_placeholders,
    unsubscribe,
    unsubscribe_by_admin,
    update_draft,
)

__all__ = [
    "AUDIENCE",
    "DELIVERY_KIND",
    "DELIVERY_STATUS",
    "LETTER_STATUS",
    "MESSAGE_ROLE",
    "REPLY_TO_MODE",
    "SUBSCRIBER_SOURCE",
    "SUBSCRIBER_STATUS",
    "Audience",
    "DeliveryKind",
    "DeliveryStatus",
    "LetterStatus",
    "MessageRole",
    "ReplyToMode",
    "SubscriberSource",
    "SubscriberStatus",
    "Delivery",
    "DraftingMessage",
    "Newsletter",
    "Subscriber",
    "DraftingError",
    "apply_proposal",
    "ask_raakje",
    "dismiss_proposal",
    "display_proposal",
    "get_drafting_message",
    "record_turn",
    "SEND_JOB",
    "NewsletterError",
    "activity_facts",
    "activity_block_html",
    "activity_card_html",
    "activity_line_html",
    "expand_blocks",
    "add_attachment",
    "add_by_admin",
    "audience_counts",
    "audience_summary",
    "CALENDAR_DEFAULT",
    "FEATURED_MAX",
    "GROUPS",
    "Choices",
    "choices_of",
    "default_choices",
    "draft_subject",
    "set_choice",
    "calendar_html",
    "closing_html",
    "confirm",
    "copy_newsletter",
    "create_newsletter",
    "deliveries_of",
    "delete_draft",
    "erase",
    "expected_days",
    "get_newsletter",
    "greeting_html",
    "insertable_activities",
    "list_newsletters",
    "list_subscribers",
    "member_addresses",
    "messages_of",
    "plain_text",
    "preview_import",
    "preview_text_of",
    "progress_of",
    "render_text",
    "recipients_for",
    "render_mail",
    "resubscribe",
    "run_import",
    "save_settings",
    "send_batch",
    "send_test",
    "set_draft_sources",
    "reports_since_previous_letter",
    "short_date",
    "start_sending",
    "subscribe_public",
    "subscriber_by_confirm_token",
    "subscriber_by_unsubscribe_token",
    "subscriber_counts",
    "unsubscribe",
    "unsubscribe_by_admin",
    "update_draft",
    "placeholder_refusal",
    "unfilled_placeholders",
]
